/* Generated by Yosys 0.47+56 (git sha1 bbb6bbd12, clang++ 13.0.1 -fPIC -O3) */

(* top =  1  *)
(* src = "counter.v:1.1-13.10" *)
module counter(clk, reset, count);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  (* src = "counter.v:2.17-2.20" *)
  input clk;
  wire clk;
  (* src = "counter.v:4.24-4.29" *)
  output [7:0] count;
  wire [7:0] count;
  (* src = "counter.v:3.17-3.22" *)
  input reset;
  wire reset;
  sky130_fd_sc_hd__and3_1 _20_ (
    .A(count[0]),
    .B(count[1]),
    .C(count[2]),
    .X(_08_)
  );
  sky130_fd_sc_hd__and4_1 _21_ (
    .A(count[0]),
    .B(count[1]),
    .C(count[2]),
    .D(count[3]),
    .X(_09_)
  );
  sky130_fd_sc_hd__and2_0 _22_ (
    .A(count[4]),
    .B(_09_),
    .X(_10_)
  );
  sky130_fd_sc_hd__and3_1 _23_ (
    .A(count[4]),
    .B(count[5]),
    .C(_09_),
    .X(_11_)
  );
  sky130_fd_sc_hd__o21bai_1 _24_ (
    .A1(count[6]),
    .A2(_11_),
    .B1_N(reset),
    .Y(_12_)
  );
  sky130_fd_sc_hd__a21oi_1 _25_ (
    .A1(count[6]),
    .A2(_11_),
    .B1(_12_),
    .Y(_00_)
  );
  sky130_fd_sc_hd__and3_1 _26_ (
    .A(count[6]),
    .B(count[7]),
    .C(_11_),
    .X(_13_)
  );
  sky130_fd_sc_hd__a21oi_1 _27_ (
    .A1(count[6]),
    .A2(_11_),
    .B1(count[7]),
    .Y(_14_)
  );
  sky130_fd_sc_hd__nor3_1 _28_ (
    .A(reset),
    .B(_13_),
    .C(_14_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__nor2_1 _29_ (
    .A(count[0]),
    .B(reset),
    .Y(_02_)
  );
  sky130_fd_sc_hd__a21oi_1 _30_ (
    .A1(count[0]),
    .A2(count[1]),
    .B1(reset),
    .Y(_15_)
  );
  sky130_fd_sc_hd__o21a_1 _31_ (
    .A1(count[0]),
    .A2(count[1]),
    .B1(_15_),
    .X(_03_)
  );
  sky130_fd_sc_hd__a21oi_1 _32_ (
    .A1(count[0]),
    .A2(count[1]),
    .B1(count[2]),
    .Y(_16_)
  );
  sky130_fd_sc_hd__nor3_1 _33_ (
    .A(reset),
    .B(_08_),
    .C(_16_),
    .Y(_04_)
  );
  sky130_fd_sc_hd__nor2_1 _34_ (
    .A(count[3]),
    .B(_08_),
    .Y(_17_)
  );
  sky130_fd_sc_hd__nor3_1 _35_ (
    .A(reset),
    .B(_09_),
    .C(_17_),
    .Y(_05_)
  );
  sky130_fd_sc_hd__nor2_1 _36_ (
    .A(count[4]),
    .B(_09_),
    .Y(_18_)
  );
  sky130_fd_sc_hd__nor3_1 _37_ (
    .A(reset),
    .B(_10_),
    .C(_18_),
    .Y(_06_)
  );
  sky130_fd_sc_hd__nor2_1 _38_ (
    .A(count[5]),
    .B(_10_),
    .Y(_19_)
  );
  sky130_fd_sc_hd__nor3_1 _39_ (
    .A(reset),
    .B(_11_),
    .C(_19_),
    .Y(_07_)
  );
  (* src = "counter.v:6.5-11.8" *)
  sky130_fd_sc_hd__dfxtp_1 _40_ (
    .CLK(clk),
    .D(_00_),
    .Q(count[6])
  );
  (* src = "counter.v:6.5-11.8" *)
  sky130_fd_sc_hd__dfxtp_1 _41_ (
    .CLK(clk),
    .D(_01_),
    .Q(count[7])
  );
  (* src = "counter.v:6.5-11.8" *)
  sky130_fd_sc_hd__dfxtp_1 _42_ (
    .CLK(clk),
    .D(_02_),
    .Q(count[0])
  );
  (* src = "counter.v:6.5-11.8" *)
  sky130_fd_sc_hd__dfxtp_1 _43_ (
    .CLK(clk),
    .D(_03_),
    .Q(count[1])
  );
  (* src = "counter.v:6.5-11.8" *)
  sky130_fd_sc_hd__dfxtp_1 _44_ (
    .CLK(clk),
    .D(_04_),
    .Q(count[2])
  );
  (* src = "counter.v:6.5-11.8" *)
  sky130_fd_sc_hd__dfxtp_1 _45_ (
    .CLK(clk),
    .D(_05_),
    .Q(count[3])
  );
  (* src = "counter.v:6.5-11.8" *)
  sky130_fd_sc_hd__dfxtp_1 _46_ (
    .CLK(clk),
    .D(_06_),
    .Q(count[4])
  );
  (* src = "counter.v:6.5-11.8" *)
  sky130_fd_sc_hd__dfxtp_1 _47_ (
    .CLK(clk),
    .D(_07_),
    .Q(count[5])
  );
endmodule
