/* Generated by Yosys 0.47+56 (git sha1 bbb6bbd12, clang++ 13.0.1 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "single_row_adc.v:1.1-42.10" *)
module single_row_adc(clk, reset, comp, stored_values);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  wire _377_;
  wire _378_;
  wire _379_;
  wire _380_;
  wire _381_;
  wire _382_;
  wire _383_;
  wire _384_;
  wire _385_;
  wire _386_;
  wire _387_;
  wire _388_;
  wire _389_;
  wire _390_;
  wire _391_;
  wire _392_;
  wire _393_;
  (* force_downto = 32'd1 *)
  (* src = "single_row_adc.v:21.24-21.35|/foss/tools/yosys_new/oss-cad-suite/yosys/share/techmap.v:270.23-270.24" *)
  wire [7:0] _394_;
  (* force_downto = 32'd1 *)
  (* src = "single_row_adc.v:21.24-21.35|/foss/tools/yosys_new/oss-cad-suite/yosys/share/techmap.v:270.26-270.27" *)
  wire [7:0] _395_;
  (* src = "single_row_adc.v:4.17-4.20" *)
  input clk;
  wire clk;
  (* src = "single_row_adc.v:6.34-6.38" *)
  input [19:0] comp;
  wire [19:0] comp;
  (* src = "single_row_adc.v:14.28-14.37" *)
  wire [19:0] comp_prev;
  (* src = "single_row_adc.v:11.17-11.24" *)
  wire [7:0] counter;
  (* src = "single_row_adc.v:5.17-5.22" *)
  input reset;
  wire reset;
  (* src = "single_row_adc.v:7.41-7.54" *)
  output [159:0] stored_values;
  wire [159:0] stored_values;
  sky130_fd_sc_hd__clkinv_1 _396_ (
    .A(counter[0]),
    .Y(_394_[0])
  );
  sky130_fd_sc_hd__clkinv_1 _397_ (
    .A(reset),
    .Y(_085_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _398_ (
    .A(comp[0]),
    .SLEEP(comp_prev[0]),
    .X(_348_)
  );
  sky130_fd_sc_hd__mux2_1 _399_ (
    .A0(stored_values[7]),
    .A1(counter[7]),
    .S(_348_),
    .X(_243_)
  );
  sky130_fd_sc_hd__mux2_1 _400_ (
    .A0(stored_values[6]),
    .A1(counter[6]),
    .S(_348_),
    .X(_242_)
  );
  sky130_fd_sc_hd__mux2_1 _401_ (
    .A0(stored_values[5]),
    .A1(counter[5]),
    .S(_348_),
    .X(_241_)
  );
  sky130_fd_sc_hd__mux2_1 _402_ (
    .A0(stored_values[4]),
    .A1(counter[4]),
    .S(_348_),
    .X(_240_)
  );
  sky130_fd_sc_hd__mux2_1 _403_ (
    .A0(stored_values[3]),
    .A1(counter[3]),
    .S(_348_),
    .X(_239_)
  );
  sky130_fd_sc_hd__mux2_1 _404_ (
    .A0(stored_values[2]),
    .A1(counter[2]),
    .S(_348_),
    .X(_238_)
  );
  sky130_fd_sc_hd__mux2_1 _405_ (
    .A0(stored_values[1]),
    .A1(counter[1]),
    .S(_348_),
    .X(_237_)
  );
  sky130_fd_sc_hd__nor2_1 _406_ (
    .A(stored_values[0]),
    .B(_348_),
    .Y(_349_)
  );
  sky130_fd_sc_hd__a21oi_1 _407_ (
    .A1(_394_[0]),
    .A2(_348_),
    .B1(_349_),
    .Y(_236_)
  );
  sky130_fd_sc_hd__nand2b_1 _408_ (
    .A_N(comp_prev[1]),
    .B(comp[1]),
    .Y(_350_)
  );
  sky130_fd_sc_hd__mux2_1 _409_ (
    .A0(counter[7]),
    .A1(stored_values[15]),
    .S(_350_),
    .X(_235_)
  );
  sky130_fd_sc_hd__mux2_1 _410_ (
    .A0(counter[6]),
    .A1(stored_values[14]),
    .S(_350_),
    .X(_234_)
  );
  sky130_fd_sc_hd__mux2_1 _411_ (
    .A0(counter[5]),
    .A1(stored_values[13]),
    .S(_350_),
    .X(_233_)
  );
  sky130_fd_sc_hd__mux2_1 _412_ (
    .A0(counter[4]),
    .A1(stored_values[12]),
    .S(_350_),
    .X(_232_)
  );
  sky130_fd_sc_hd__mux2_1 _413_ (
    .A0(counter[3]),
    .A1(stored_values[11]),
    .S(_350_),
    .X(_231_)
  );
  sky130_fd_sc_hd__mux2_1 _414_ (
    .A0(counter[2]),
    .A1(stored_values[10]),
    .S(_350_),
    .X(_230_)
  );
  sky130_fd_sc_hd__mux2_1 _415_ (
    .A0(counter[1]),
    .A1(stored_values[9]),
    .S(_350_),
    .X(_229_)
  );
  sky130_fd_sc_hd__nand2_1 _416_ (
    .A(stored_values[8]),
    .B(_350_),
    .Y(_351_)
  );
  sky130_fd_sc_hd__o21ai_0 _417_ (
    .A1(_394_[0]),
    .A2(_350_),
    .B1(_351_),
    .Y(_228_)
  );
  sky130_fd_sc_hd__nand2b_1 _418_ (
    .A_N(comp_prev[2]),
    .B(comp[2]),
    .Y(_352_)
  );
  sky130_fd_sc_hd__mux2_1 _419_ (
    .A0(counter[7]),
    .A1(stored_values[23]),
    .S(_352_),
    .X(_227_)
  );
  sky130_fd_sc_hd__mux2_1 _420_ (
    .A0(counter[6]),
    .A1(stored_values[22]),
    .S(_352_),
    .X(_226_)
  );
  sky130_fd_sc_hd__mux2_1 _421_ (
    .A0(counter[5]),
    .A1(stored_values[21]),
    .S(_352_),
    .X(_225_)
  );
  sky130_fd_sc_hd__mux2_1 _422_ (
    .A0(counter[4]),
    .A1(stored_values[20]),
    .S(_352_),
    .X(_224_)
  );
  sky130_fd_sc_hd__mux2_1 _423_ (
    .A0(counter[3]),
    .A1(stored_values[19]),
    .S(_352_),
    .X(_223_)
  );
  sky130_fd_sc_hd__mux2_1 _424_ (
    .A0(counter[2]),
    .A1(stored_values[18]),
    .S(_352_),
    .X(_222_)
  );
  sky130_fd_sc_hd__mux2_1 _425_ (
    .A0(counter[1]),
    .A1(stored_values[17]),
    .S(_352_),
    .X(_221_)
  );
  sky130_fd_sc_hd__nand2_1 _426_ (
    .A(stored_values[16]),
    .B(_352_),
    .Y(_353_)
  );
  sky130_fd_sc_hd__o21ai_0 _427_ (
    .A1(_394_[0]),
    .A2(_352_),
    .B1(_353_),
    .Y(_220_)
  );
  sky130_fd_sc_hd__nand2b_1 _428_ (
    .A_N(comp_prev[3]),
    .B(comp[3]),
    .Y(_354_)
  );
  sky130_fd_sc_hd__mux2_1 _429_ (
    .A0(counter[7]),
    .A1(stored_values[31]),
    .S(_354_),
    .X(_219_)
  );
  sky130_fd_sc_hd__mux2_1 _430_ (
    .A0(counter[6]),
    .A1(stored_values[30]),
    .S(_354_),
    .X(_218_)
  );
  sky130_fd_sc_hd__mux2_1 _431_ (
    .A0(counter[5]),
    .A1(stored_values[29]),
    .S(_354_),
    .X(_217_)
  );
  sky130_fd_sc_hd__mux2_1 _432_ (
    .A0(counter[4]),
    .A1(stored_values[28]),
    .S(_354_),
    .X(_216_)
  );
  sky130_fd_sc_hd__mux2_1 _433_ (
    .A0(counter[3]),
    .A1(stored_values[27]),
    .S(_354_),
    .X(_215_)
  );
  sky130_fd_sc_hd__mux2_1 _434_ (
    .A0(counter[2]),
    .A1(stored_values[26]),
    .S(_354_),
    .X(_214_)
  );
  sky130_fd_sc_hd__mux2_1 _435_ (
    .A0(counter[1]),
    .A1(stored_values[25]),
    .S(_354_),
    .X(_213_)
  );
  sky130_fd_sc_hd__nand2_1 _436_ (
    .A(stored_values[24]),
    .B(_354_),
    .Y(_355_)
  );
  sky130_fd_sc_hd__o21ai_0 _437_ (
    .A1(_394_[0]),
    .A2(_354_),
    .B1(_355_),
    .Y(_212_)
  );
  sky130_fd_sc_hd__nand2b_1 _438_ (
    .A_N(comp_prev[4]),
    .B(comp[4]),
    .Y(_356_)
  );
  sky130_fd_sc_hd__mux2_1 _439_ (
    .A0(counter[7]),
    .A1(stored_values[39]),
    .S(_356_),
    .X(_211_)
  );
  sky130_fd_sc_hd__mux2_1 _440_ (
    .A0(counter[6]),
    .A1(stored_values[38]),
    .S(_356_),
    .X(_210_)
  );
  sky130_fd_sc_hd__mux2_1 _441_ (
    .A0(counter[5]),
    .A1(stored_values[37]),
    .S(_356_),
    .X(_209_)
  );
  sky130_fd_sc_hd__mux2_1 _442_ (
    .A0(counter[4]),
    .A1(stored_values[36]),
    .S(_356_),
    .X(_208_)
  );
  sky130_fd_sc_hd__mux2_1 _443_ (
    .A0(counter[3]),
    .A1(stored_values[35]),
    .S(_356_),
    .X(_207_)
  );
  sky130_fd_sc_hd__mux2_1 _444_ (
    .A0(counter[2]),
    .A1(stored_values[34]),
    .S(_356_),
    .X(_206_)
  );
  sky130_fd_sc_hd__mux2_1 _445_ (
    .A0(counter[1]),
    .A1(stored_values[33]),
    .S(_356_),
    .X(_205_)
  );
  sky130_fd_sc_hd__nand2_1 _446_ (
    .A(stored_values[32]),
    .B(_356_),
    .Y(_357_)
  );
  sky130_fd_sc_hd__o21ai_0 _447_ (
    .A1(_394_[0]),
    .A2(_356_),
    .B1(_357_),
    .Y(_204_)
  );
  sky130_fd_sc_hd__nand2b_1 _448_ (
    .A_N(comp_prev[5]),
    .B(comp[5]),
    .Y(_358_)
  );
  sky130_fd_sc_hd__mux2_1 _449_ (
    .A0(counter[7]),
    .A1(stored_values[47]),
    .S(_358_),
    .X(_203_)
  );
  sky130_fd_sc_hd__mux2_1 _450_ (
    .A0(counter[6]),
    .A1(stored_values[46]),
    .S(_358_),
    .X(_202_)
  );
  sky130_fd_sc_hd__mux2_1 _451_ (
    .A0(counter[5]),
    .A1(stored_values[45]),
    .S(_358_),
    .X(_201_)
  );
  sky130_fd_sc_hd__mux2_1 _452_ (
    .A0(counter[4]),
    .A1(stored_values[44]),
    .S(_358_),
    .X(_200_)
  );
  sky130_fd_sc_hd__mux2_1 _453_ (
    .A0(counter[3]),
    .A1(stored_values[43]),
    .S(_358_),
    .X(_199_)
  );
  sky130_fd_sc_hd__mux2_1 _454_ (
    .A0(counter[2]),
    .A1(stored_values[42]),
    .S(_358_),
    .X(_198_)
  );
  sky130_fd_sc_hd__mux2_1 _455_ (
    .A0(counter[1]),
    .A1(stored_values[41]),
    .S(_358_),
    .X(_197_)
  );
  sky130_fd_sc_hd__nand2_1 _456_ (
    .A(stored_values[40]),
    .B(_358_),
    .Y(_359_)
  );
  sky130_fd_sc_hd__o21ai_0 _457_ (
    .A1(_394_[0]),
    .A2(_358_),
    .B1(_359_),
    .Y(_196_)
  );
  sky130_fd_sc_hd__nand2b_1 _458_ (
    .A_N(comp_prev[6]),
    .B(comp[6]),
    .Y(_360_)
  );
  sky130_fd_sc_hd__mux2_1 _459_ (
    .A0(counter[7]),
    .A1(stored_values[55]),
    .S(_360_),
    .X(_195_)
  );
  sky130_fd_sc_hd__mux2_1 _460_ (
    .A0(counter[6]),
    .A1(stored_values[54]),
    .S(_360_),
    .X(_194_)
  );
  sky130_fd_sc_hd__mux2_1 _461_ (
    .A0(counter[5]),
    .A1(stored_values[53]),
    .S(_360_),
    .X(_193_)
  );
  sky130_fd_sc_hd__mux2_1 _462_ (
    .A0(counter[4]),
    .A1(stored_values[52]),
    .S(_360_),
    .X(_192_)
  );
  sky130_fd_sc_hd__mux2_1 _463_ (
    .A0(counter[3]),
    .A1(stored_values[51]),
    .S(_360_),
    .X(_191_)
  );
  sky130_fd_sc_hd__mux2_1 _464_ (
    .A0(counter[2]),
    .A1(stored_values[50]),
    .S(_360_),
    .X(_190_)
  );
  sky130_fd_sc_hd__mux2_1 _465_ (
    .A0(counter[1]),
    .A1(stored_values[49]),
    .S(_360_),
    .X(_189_)
  );
  sky130_fd_sc_hd__nand2_1 _466_ (
    .A(stored_values[48]),
    .B(_360_),
    .Y(_361_)
  );
  sky130_fd_sc_hd__o21ai_0 _467_ (
    .A1(_394_[0]),
    .A2(_360_),
    .B1(_361_),
    .Y(_188_)
  );
  sky130_fd_sc_hd__nand2b_1 _468_ (
    .A_N(comp_prev[7]),
    .B(comp[7]),
    .Y(_362_)
  );
  sky130_fd_sc_hd__mux2_1 _469_ (
    .A0(counter[7]),
    .A1(stored_values[63]),
    .S(_362_),
    .X(_347_)
  );
  sky130_fd_sc_hd__mux2_1 _470_ (
    .A0(counter[6]),
    .A1(stored_values[62]),
    .S(_362_),
    .X(_346_)
  );
  sky130_fd_sc_hd__mux2_1 _471_ (
    .A0(counter[5]),
    .A1(stored_values[61]),
    .S(_362_),
    .X(_345_)
  );
  sky130_fd_sc_hd__mux2_1 _472_ (
    .A0(counter[4]),
    .A1(stored_values[60]),
    .S(_362_),
    .X(_344_)
  );
  sky130_fd_sc_hd__mux2_1 _473_ (
    .A0(counter[3]),
    .A1(stored_values[59]),
    .S(_362_),
    .X(_343_)
  );
  sky130_fd_sc_hd__mux2_1 _474_ (
    .A0(counter[2]),
    .A1(stored_values[58]),
    .S(_362_),
    .X(_342_)
  );
  sky130_fd_sc_hd__mux2_1 _475_ (
    .A0(counter[1]),
    .A1(stored_values[57]),
    .S(_362_),
    .X(_341_)
  );
  sky130_fd_sc_hd__nand2_1 _476_ (
    .A(stored_values[56]),
    .B(_362_),
    .Y(_363_)
  );
  sky130_fd_sc_hd__o21ai_0 _477_ (
    .A1(_394_[0]),
    .A2(_362_),
    .B1(_363_),
    .Y(_340_)
  );
  sky130_fd_sc_hd__nand2b_1 _478_ (
    .A_N(comp_prev[8]),
    .B(comp[8]),
    .Y(_364_)
  );
  sky130_fd_sc_hd__mux2_1 _479_ (
    .A0(counter[7]),
    .A1(stored_values[71]),
    .S(_364_),
    .X(_339_)
  );
  sky130_fd_sc_hd__mux2_1 _480_ (
    .A0(counter[6]),
    .A1(stored_values[70]),
    .S(_364_),
    .X(_338_)
  );
  sky130_fd_sc_hd__mux2_1 _481_ (
    .A0(counter[5]),
    .A1(stored_values[69]),
    .S(_364_),
    .X(_337_)
  );
  sky130_fd_sc_hd__mux2_1 _482_ (
    .A0(counter[4]),
    .A1(stored_values[68]),
    .S(_364_),
    .X(_336_)
  );
  sky130_fd_sc_hd__mux2_1 _483_ (
    .A0(counter[3]),
    .A1(stored_values[67]),
    .S(_364_),
    .X(_335_)
  );
  sky130_fd_sc_hd__mux2_1 _484_ (
    .A0(counter[2]),
    .A1(stored_values[66]),
    .S(_364_),
    .X(_334_)
  );
  sky130_fd_sc_hd__mux2_1 _485_ (
    .A0(counter[1]),
    .A1(stored_values[65]),
    .S(_364_),
    .X(_333_)
  );
  sky130_fd_sc_hd__nand2_1 _486_ (
    .A(stored_values[64]),
    .B(_364_),
    .Y(_365_)
  );
  sky130_fd_sc_hd__o21ai_0 _487_ (
    .A1(_394_[0]),
    .A2(_364_),
    .B1(_365_),
    .Y(_332_)
  );
  sky130_fd_sc_hd__nand2b_1 _488_ (
    .A_N(comp_prev[9]),
    .B(comp[9]),
    .Y(_366_)
  );
  sky130_fd_sc_hd__mux2_1 _489_ (
    .A0(counter[7]),
    .A1(stored_values[79]),
    .S(_366_),
    .X(_331_)
  );
  sky130_fd_sc_hd__mux2_1 _490_ (
    .A0(counter[6]),
    .A1(stored_values[78]),
    .S(_366_),
    .X(_330_)
  );
  sky130_fd_sc_hd__mux2_1 _491_ (
    .A0(counter[5]),
    .A1(stored_values[77]),
    .S(_366_),
    .X(_329_)
  );
  sky130_fd_sc_hd__mux2_1 _492_ (
    .A0(counter[4]),
    .A1(stored_values[76]),
    .S(_366_),
    .X(_328_)
  );
  sky130_fd_sc_hd__mux2_1 _493_ (
    .A0(counter[3]),
    .A1(stored_values[75]),
    .S(_366_),
    .X(_327_)
  );
  sky130_fd_sc_hd__mux2_1 _494_ (
    .A0(counter[2]),
    .A1(stored_values[74]),
    .S(_366_),
    .X(_326_)
  );
  sky130_fd_sc_hd__mux2_1 _495_ (
    .A0(counter[1]),
    .A1(stored_values[73]),
    .S(_366_),
    .X(_325_)
  );
  sky130_fd_sc_hd__nand2_1 _496_ (
    .A(stored_values[72]),
    .B(_366_),
    .Y(_367_)
  );
  sky130_fd_sc_hd__o21ai_0 _497_ (
    .A1(_394_[0]),
    .A2(_366_),
    .B1(_367_),
    .Y(_324_)
  );
  sky130_fd_sc_hd__nand2b_1 _498_ (
    .A_N(comp_prev[10]),
    .B(comp[10]),
    .Y(_368_)
  );
  sky130_fd_sc_hd__mux2_1 _499_ (
    .A0(counter[7]),
    .A1(stored_values[87]),
    .S(_368_),
    .X(_323_)
  );
  sky130_fd_sc_hd__mux2_1 _500_ (
    .A0(counter[6]),
    .A1(stored_values[86]),
    .S(_368_),
    .X(_322_)
  );
  sky130_fd_sc_hd__mux2_1 _501_ (
    .A0(counter[5]),
    .A1(stored_values[85]),
    .S(_368_),
    .X(_321_)
  );
  sky130_fd_sc_hd__mux2_1 _502_ (
    .A0(counter[4]),
    .A1(stored_values[84]),
    .S(_368_),
    .X(_320_)
  );
  sky130_fd_sc_hd__mux2_1 _503_ (
    .A0(counter[3]),
    .A1(stored_values[83]),
    .S(_368_),
    .X(_319_)
  );
  sky130_fd_sc_hd__mux2_1 _504_ (
    .A0(counter[2]),
    .A1(stored_values[82]),
    .S(_368_),
    .X(_318_)
  );
  sky130_fd_sc_hd__mux2_1 _505_ (
    .A0(counter[1]),
    .A1(stored_values[81]),
    .S(_368_),
    .X(_317_)
  );
  sky130_fd_sc_hd__nand2_1 _506_ (
    .A(stored_values[80]),
    .B(_368_),
    .Y(_369_)
  );
  sky130_fd_sc_hd__o21ai_0 _507_ (
    .A1(_394_[0]),
    .A2(_368_),
    .B1(_369_),
    .Y(_316_)
  );
  sky130_fd_sc_hd__nand2b_1 _508_ (
    .A_N(comp_prev[11]),
    .B(comp[11]),
    .Y(_370_)
  );
  sky130_fd_sc_hd__mux2_1 _509_ (
    .A0(counter[7]),
    .A1(stored_values[95]),
    .S(_370_),
    .X(_315_)
  );
  sky130_fd_sc_hd__mux2_1 _510_ (
    .A0(counter[6]),
    .A1(stored_values[94]),
    .S(_370_),
    .X(_314_)
  );
  sky130_fd_sc_hd__mux2_1 _511_ (
    .A0(counter[5]),
    .A1(stored_values[93]),
    .S(_370_),
    .X(_313_)
  );
  sky130_fd_sc_hd__mux2_1 _512_ (
    .A0(counter[4]),
    .A1(stored_values[92]),
    .S(_370_),
    .X(_312_)
  );
  sky130_fd_sc_hd__mux2_1 _513_ (
    .A0(counter[3]),
    .A1(stored_values[91]),
    .S(_370_),
    .X(_311_)
  );
  sky130_fd_sc_hd__mux2_1 _514_ (
    .A0(counter[2]),
    .A1(stored_values[90]),
    .S(_370_),
    .X(_310_)
  );
  sky130_fd_sc_hd__mux2_1 _515_ (
    .A0(counter[1]),
    .A1(stored_values[89]),
    .S(_370_),
    .X(_309_)
  );
  sky130_fd_sc_hd__nand2_1 _516_ (
    .A(stored_values[88]),
    .B(_370_),
    .Y(_371_)
  );
  sky130_fd_sc_hd__o21ai_0 _517_ (
    .A1(_394_[0]),
    .A2(_370_),
    .B1(_371_),
    .Y(_308_)
  );
  sky130_fd_sc_hd__nand2b_1 _518_ (
    .A_N(comp_prev[12]),
    .B(comp[12]),
    .Y(_372_)
  );
  sky130_fd_sc_hd__mux2_1 _519_ (
    .A0(counter[7]),
    .A1(stored_values[103]),
    .S(_372_),
    .X(_307_)
  );
  sky130_fd_sc_hd__mux2_1 _520_ (
    .A0(counter[6]),
    .A1(stored_values[102]),
    .S(_372_),
    .X(_306_)
  );
  sky130_fd_sc_hd__mux2_1 _521_ (
    .A0(counter[5]),
    .A1(stored_values[101]),
    .S(_372_),
    .X(_305_)
  );
  sky130_fd_sc_hd__mux2_1 _522_ (
    .A0(counter[4]),
    .A1(stored_values[100]),
    .S(_372_),
    .X(_304_)
  );
  sky130_fd_sc_hd__mux2_1 _523_ (
    .A0(counter[3]),
    .A1(stored_values[99]),
    .S(_372_),
    .X(_303_)
  );
  sky130_fd_sc_hd__mux2_1 _524_ (
    .A0(counter[2]),
    .A1(stored_values[98]),
    .S(_372_),
    .X(_302_)
  );
  sky130_fd_sc_hd__mux2_1 _525_ (
    .A0(counter[1]),
    .A1(stored_values[97]),
    .S(_372_),
    .X(_301_)
  );
  sky130_fd_sc_hd__nand2_1 _526_ (
    .A(stored_values[96]),
    .B(_372_),
    .Y(_373_)
  );
  sky130_fd_sc_hd__o21ai_0 _527_ (
    .A1(_394_[0]),
    .A2(_372_),
    .B1(_373_),
    .Y(_300_)
  );
  sky130_fd_sc_hd__nand2b_1 _528_ (
    .A_N(comp_prev[13]),
    .B(comp[13]),
    .Y(_374_)
  );
  sky130_fd_sc_hd__mux2_1 _529_ (
    .A0(counter[7]),
    .A1(stored_values[111]),
    .S(_374_),
    .X(_299_)
  );
  sky130_fd_sc_hd__mux2_1 _530_ (
    .A0(counter[6]),
    .A1(stored_values[110]),
    .S(_374_),
    .X(_298_)
  );
  sky130_fd_sc_hd__mux2_1 _531_ (
    .A0(counter[5]),
    .A1(stored_values[109]),
    .S(_374_),
    .X(_297_)
  );
  sky130_fd_sc_hd__mux2_1 _532_ (
    .A0(counter[4]),
    .A1(stored_values[108]),
    .S(_374_),
    .X(_296_)
  );
  sky130_fd_sc_hd__mux2_1 _533_ (
    .A0(counter[3]),
    .A1(stored_values[107]),
    .S(_374_),
    .X(_295_)
  );
  sky130_fd_sc_hd__mux2_1 _534_ (
    .A0(counter[2]),
    .A1(stored_values[106]),
    .S(_374_),
    .X(_294_)
  );
  sky130_fd_sc_hd__mux2_1 _535_ (
    .A0(counter[1]),
    .A1(stored_values[105]),
    .S(_374_),
    .X(_293_)
  );
  sky130_fd_sc_hd__nand2_1 _536_ (
    .A(stored_values[104]),
    .B(_374_),
    .Y(_375_)
  );
  sky130_fd_sc_hd__o21ai_0 _537_ (
    .A1(_394_[0]),
    .A2(_374_),
    .B1(_375_),
    .Y(_292_)
  );
  sky130_fd_sc_hd__nand2b_1 _538_ (
    .A_N(comp_prev[14]),
    .B(comp[14]),
    .Y(_376_)
  );
  sky130_fd_sc_hd__mux2_1 _539_ (
    .A0(counter[7]),
    .A1(stored_values[119]),
    .S(_376_),
    .X(_291_)
  );
  sky130_fd_sc_hd__mux2_1 _540_ (
    .A0(counter[6]),
    .A1(stored_values[118]),
    .S(_376_),
    .X(_290_)
  );
  sky130_fd_sc_hd__mux2_1 _541_ (
    .A0(counter[5]),
    .A1(stored_values[117]),
    .S(_376_),
    .X(_289_)
  );
  sky130_fd_sc_hd__mux2_1 _542_ (
    .A0(counter[4]),
    .A1(stored_values[116]),
    .S(_376_),
    .X(_288_)
  );
  sky130_fd_sc_hd__mux2_1 _543_ (
    .A0(counter[3]),
    .A1(stored_values[115]),
    .S(_376_),
    .X(_287_)
  );
  sky130_fd_sc_hd__mux2_1 _544_ (
    .A0(counter[2]),
    .A1(stored_values[114]),
    .S(_376_),
    .X(_286_)
  );
  sky130_fd_sc_hd__mux2_1 _545_ (
    .A0(counter[1]),
    .A1(stored_values[113]),
    .S(_376_),
    .X(_285_)
  );
  sky130_fd_sc_hd__nand2_1 _546_ (
    .A(stored_values[112]),
    .B(_376_),
    .Y(_377_)
  );
  sky130_fd_sc_hd__o21ai_0 _547_ (
    .A1(_394_[0]),
    .A2(_376_),
    .B1(_377_),
    .Y(_284_)
  );
  sky130_fd_sc_hd__nand2b_1 _548_ (
    .A_N(comp_prev[15]),
    .B(comp[15]),
    .Y(_378_)
  );
  sky130_fd_sc_hd__mux2_1 _549_ (
    .A0(counter[7]),
    .A1(stored_values[127]),
    .S(_378_),
    .X(_283_)
  );
  sky130_fd_sc_hd__mux2_1 _550_ (
    .A0(counter[6]),
    .A1(stored_values[126]),
    .S(_378_),
    .X(_282_)
  );
  sky130_fd_sc_hd__mux2_1 _551_ (
    .A0(counter[5]),
    .A1(stored_values[125]),
    .S(_378_),
    .X(_281_)
  );
  sky130_fd_sc_hd__mux2_1 _552_ (
    .A0(counter[4]),
    .A1(stored_values[124]),
    .S(_378_),
    .X(_280_)
  );
  sky130_fd_sc_hd__mux2_1 _553_ (
    .A0(counter[3]),
    .A1(stored_values[123]),
    .S(_378_),
    .X(_279_)
  );
  sky130_fd_sc_hd__mux2_1 _554_ (
    .A0(counter[2]),
    .A1(stored_values[122]),
    .S(_378_),
    .X(_278_)
  );
  sky130_fd_sc_hd__mux2_1 _555_ (
    .A0(counter[1]),
    .A1(stored_values[121]),
    .S(_378_),
    .X(_277_)
  );
  sky130_fd_sc_hd__nand2_1 _556_ (
    .A(stored_values[120]),
    .B(_378_),
    .Y(_379_)
  );
  sky130_fd_sc_hd__o21ai_0 _557_ (
    .A1(_394_[0]),
    .A2(_378_),
    .B1(_379_),
    .Y(_276_)
  );
  sky130_fd_sc_hd__nand2b_1 _558_ (
    .A_N(comp_prev[16]),
    .B(comp[16]),
    .Y(_380_)
  );
  sky130_fd_sc_hd__mux2_1 _559_ (
    .A0(counter[7]),
    .A1(stored_values[135]),
    .S(_380_),
    .X(_275_)
  );
  sky130_fd_sc_hd__mux2_1 _560_ (
    .A0(counter[6]),
    .A1(stored_values[134]),
    .S(_380_),
    .X(_274_)
  );
  sky130_fd_sc_hd__mux2_1 _561_ (
    .A0(counter[5]),
    .A1(stored_values[133]),
    .S(_380_),
    .X(_273_)
  );
  sky130_fd_sc_hd__mux2_1 _562_ (
    .A0(counter[4]),
    .A1(stored_values[132]),
    .S(_380_),
    .X(_272_)
  );
  sky130_fd_sc_hd__mux2_1 _563_ (
    .A0(counter[3]),
    .A1(stored_values[131]),
    .S(_380_),
    .X(_271_)
  );
  sky130_fd_sc_hd__mux2_1 _564_ (
    .A0(counter[2]),
    .A1(stored_values[130]),
    .S(_380_),
    .X(_270_)
  );
  sky130_fd_sc_hd__mux2_1 _565_ (
    .A0(counter[1]),
    .A1(stored_values[129]),
    .S(_380_),
    .X(_269_)
  );
  sky130_fd_sc_hd__nand2_1 _566_ (
    .A(stored_values[128]),
    .B(_380_),
    .Y(_381_)
  );
  sky130_fd_sc_hd__o21ai_0 _567_ (
    .A1(_394_[0]),
    .A2(_380_),
    .B1(_381_),
    .Y(_268_)
  );
  sky130_fd_sc_hd__nand2b_1 _568_ (
    .A_N(comp_prev[17]),
    .B(comp[17]),
    .Y(_382_)
  );
  sky130_fd_sc_hd__mux2_1 _569_ (
    .A0(counter[7]),
    .A1(stored_values[143]),
    .S(_382_),
    .X(_267_)
  );
  sky130_fd_sc_hd__mux2_1 _570_ (
    .A0(counter[6]),
    .A1(stored_values[142]),
    .S(_382_),
    .X(_266_)
  );
  sky130_fd_sc_hd__mux2_1 _571_ (
    .A0(counter[5]),
    .A1(stored_values[141]),
    .S(_382_),
    .X(_265_)
  );
  sky130_fd_sc_hd__mux2_1 _572_ (
    .A0(counter[4]),
    .A1(stored_values[140]),
    .S(_382_),
    .X(_264_)
  );
  sky130_fd_sc_hd__mux2_1 _573_ (
    .A0(counter[3]),
    .A1(stored_values[139]),
    .S(_382_),
    .X(_263_)
  );
  sky130_fd_sc_hd__mux2_1 _574_ (
    .A0(counter[2]),
    .A1(stored_values[138]),
    .S(_382_),
    .X(_262_)
  );
  sky130_fd_sc_hd__mux2_1 _575_ (
    .A0(counter[1]),
    .A1(stored_values[137]),
    .S(_382_),
    .X(_261_)
  );
  sky130_fd_sc_hd__nand2_1 _576_ (
    .A(stored_values[136]),
    .B(_382_),
    .Y(_383_)
  );
  sky130_fd_sc_hd__o21ai_0 _577_ (
    .A1(_394_[0]),
    .A2(_382_),
    .B1(_383_),
    .Y(_260_)
  );
  sky130_fd_sc_hd__nand2b_1 _578_ (
    .A_N(comp_prev[18]),
    .B(comp[18]),
    .Y(_384_)
  );
  sky130_fd_sc_hd__mux2_1 _579_ (
    .A0(counter[7]),
    .A1(stored_values[151]),
    .S(_384_),
    .X(_259_)
  );
  sky130_fd_sc_hd__mux2_1 _580_ (
    .A0(counter[6]),
    .A1(stored_values[150]),
    .S(_384_),
    .X(_258_)
  );
  sky130_fd_sc_hd__mux2_1 _581_ (
    .A0(counter[5]),
    .A1(stored_values[149]),
    .S(_384_),
    .X(_257_)
  );
  sky130_fd_sc_hd__mux2_1 _582_ (
    .A0(counter[4]),
    .A1(stored_values[148]),
    .S(_384_),
    .X(_256_)
  );
  sky130_fd_sc_hd__mux2_1 _583_ (
    .A0(counter[3]),
    .A1(stored_values[147]),
    .S(_384_),
    .X(_255_)
  );
  sky130_fd_sc_hd__mux2_1 _584_ (
    .A0(counter[2]),
    .A1(stored_values[146]),
    .S(_384_),
    .X(_254_)
  );
  sky130_fd_sc_hd__mux2_1 _585_ (
    .A0(counter[1]),
    .A1(stored_values[145]),
    .S(_384_),
    .X(_253_)
  );
  sky130_fd_sc_hd__nand2_1 _586_ (
    .A(stored_values[144]),
    .B(_384_),
    .Y(_385_)
  );
  sky130_fd_sc_hd__o21ai_0 _587_ (
    .A1(_394_[0]),
    .A2(_384_),
    .B1(_385_),
    .Y(_252_)
  );
  sky130_fd_sc_hd__nand2b_1 _588_ (
    .A_N(comp_prev[19]),
    .B(comp[19]),
    .Y(_386_)
  );
  sky130_fd_sc_hd__mux2_1 _589_ (
    .A0(counter[7]),
    .A1(stored_values[159]),
    .S(_386_),
    .X(_251_)
  );
  sky130_fd_sc_hd__mux2_1 _590_ (
    .A0(counter[6]),
    .A1(stored_values[158]),
    .S(_386_),
    .X(_250_)
  );
  sky130_fd_sc_hd__mux2_1 _591_ (
    .A0(counter[5]),
    .A1(stored_values[157]),
    .S(_386_),
    .X(_249_)
  );
  sky130_fd_sc_hd__mux2_1 _592_ (
    .A0(counter[4]),
    .A1(stored_values[156]),
    .S(_386_),
    .X(_248_)
  );
  sky130_fd_sc_hd__mux2_1 _593_ (
    .A0(counter[3]),
    .A1(stored_values[155]),
    .S(_386_),
    .X(_247_)
  );
  sky130_fd_sc_hd__mux2_1 _594_ (
    .A0(counter[2]),
    .A1(stored_values[154]),
    .S(_386_),
    .X(_246_)
  );
  sky130_fd_sc_hd__mux2_1 _595_ (
    .A0(counter[1]),
    .A1(stored_values[153]),
    .S(_386_),
    .X(_245_)
  );
  sky130_fd_sc_hd__nand2_1 _596_ (
    .A(stored_values[152]),
    .B(_386_),
    .Y(_387_)
  );
  sky130_fd_sc_hd__o21ai_0 _597_ (
    .A1(_394_[0]),
    .A2(_386_),
    .B1(_387_),
    .Y(_244_)
  );
  sky130_fd_sc_hd__nand2_1 _598_ (
    .A(counter[1]),
    .B(counter[0]),
    .Y(_388_)
  );
  sky130_fd_sc_hd__xor2_1 _599_ (
    .A(counter[1]),
    .B(counter[0]),
    .X(_395_[1])
  );
  sky130_fd_sc_hd__xnor2_1 _600_ (
    .A(counter[2]),
    .B(_388_),
    .Y(_395_[2])
  );
  sky130_fd_sc_hd__and4_1 _601_ (
    .A(counter[3]),
    .B(counter[2]),
    .C(counter[1]),
    .D(counter[0]),
    .X(_389_)
  );
  sky130_fd_sc_hd__a31oi_1 _602_ (
    .A1(counter[2]),
    .A2(counter[1]),
    .A3(counter[0]),
    .B1(counter[3]),
    .Y(_390_)
  );
  sky130_fd_sc_hd__nor2_1 _603_ (
    .A(_389_),
    .B(_390_),
    .Y(_395_[3])
  );
  sky130_fd_sc_hd__nand2_1 _604_ (
    .A(counter[4]),
    .B(_389_),
    .Y(_391_)
  );
  sky130_fd_sc_hd__xor2_1 _605_ (
    .A(counter[4]),
    .B(_389_),
    .X(_395_[4])
  );
  sky130_fd_sc_hd__xnor2_1 _606_ (
    .A(counter[5]),
    .B(_391_),
    .Y(_395_[5])
  );
  sky130_fd_sc_hd__nand4_1 _607_ (
    .A(counter[6]),
    .B(counter[5]),
    .C(counter[4]),
    .D(_389_),
    .Y(_392_)
  );
  sky130_fd_sc_hd__a31oi_1 _608_ (
    .A1(counter[5]),
    .A2(counter[4]),
    .A3(_389_),
    .B1(counter[6]),
    .Y(_393_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _609_ (
    .A(_392_),
    .SLEEP(_393_),
    .X(_395_[6])
  );
  sky130_fd_sc_hd__xnor2_1 _610_ (
    .A(counter[7]),
    .B(_392_),
    .Y(_395_[7])
  );
  sky130_fd_sc_hd__clkinv_1 _611_ (
    .A(reset),
    .Y(_086_)
  );
  sky130_fd_sc_hd__clkinv_1 _612_ (
    .A(reset),
    .Y(_087_)
  );
  sky130_fd_sc_hd__clkinv_1 _613_ (
    .A(reset),
    .Y(_088_)
  );
  sky130_fd_sc_hd__clkinv_1 _614_ (
    .A(reset),
    .Y(_089_)
  );
  sky130_fd_sc_hd__clkinv_1 _615_ (
    .A(reset),
    .Y(_090_)
  );
  sky130_fd_sc_hd__clkinv_1 _616_ (
    .A(reset),
    .Y(_091_)
  );
  sky130_fd_sc_hd__clkinv_1 _617_ (
    .A(reset),
    .Y(_092_)
  );
  sky130_fd_sc_hd__clkinv_1 _618_ (
    .A(reset),
    .Y(_093_)
  );
  sky130_fd_sc_hd__clkinv_1 _619_ (
    .A(reset),
    .Y(_094_)
  );
  sky130_fd_sc_hd__clkinv_1 _620_ (
    .A(reset),
    .Y(_095_)
  );
  sky130_fd_sc_hd__clkinv_1 _621_ (
    .A(reset),
    .Y(_096_)
  );
  sky130_fd_sc_hd__clkinv_1 _622_ (
    .A(reset),
    .Y(_097_)
  );
  sky130_fd_sc_hd__clkinv_1 _623_ (
    .A(reset),
    .Y(_098_)
  );
  sky130_fd_sc_hd__clkinv_1 _624_ (
    .A(reset),
    .Y(_099_)
  );
  sky130_fd_sc_hd__clkinv_1 _625_ (
    .A(reset),
    .Y(_100_)
  );
  sky130_fd_sc_hd__clkinv_1 _626_ (
    .A(reset),
    .Y(_101_)
  );
  sky130_fd_sc_hd__clkinv_1 _627_ (
    .A(reset),
    .Y(_102_)
  );
  sky130_fd_sc_hd__clkinv_1 _628_ (
    .A(reset),
    .Y(_103_)
  );
  sky130_fd_sc_hd__clkinv_1 _629_ (
    .A(reset),
    .Y(_104_)
  );
  sky130_fd_sc_hd__clkinv_1 _630_ (
    .A(reset),
    .Y(_105_)
  );
  sky130_fd_sc_hd__clkinv_1 _631_ (
    .A(reset),
    .Y(_106_)
  );
  sky130_fd_sc_hd__clkinv_1 _632_ (
    .A(reset),
    .Y(_107_)
  );
  sky130_fd_sc_hd__clkinv_1 _633_ (
    .A(reset),
    .Y(_108_)
  );
  sky130_fd_sc_hd__clkinv_1 _634_ (
    .A(reset),
    .Y(_109_)
  );
  sky130_fd_sc_hd__clkinv_1 _635_ (
    .A(reset),
    .Y(_110_)
  );
  sky130_fd_sc_hd__clkinv_1 _636_ (
    .A(reset),
    .Y(_111_)
  );
  sky130_fd_sc_hd__clkinv_1 _637_ (
    .A(reset),
    .Y(_112_)
  );
  sky130_fd_sc_hd__clkinv_1 _638_ (
    .A(reset),
    .Y(_113_)
  );
  sky130_fd_sc_hd__clkinv_1 _639_ (
    .A(reset),
    .Y(_114_)
  );
  sky130_fd_sc_hd__clkinv_1 _640_ (
    .A(reset),
    .Y(_115_)
  );
  sky130_fd_sc_hd__clkinv_1 _641_ (
    .A(reset),
    .Y(_116_)
  );
  sky130_fd_sc_hd__clkinv_1 _642_ (
    .A(reset),
    .Y(_117_)
  );
  sky130_fd_sc_hd__clkinv_1 _643_ (
    .A(reset),
    .Y(_118_)
  );
  sky130_fd_sc_hd__clkinv_1 _644_ (
    .A(reset),
    .Y(_119_)
  );
  sky130_fd_sc_hd__clkinv_1 _645_ (
    .A(reset),
    .Y(_120_)
  );
  sky130_fd_sc_hd__clkinv_1 _646_ (
    .A(reset),
    .Y(_121_)
  );
  sky130_fd_sc_hd__clkinv_1 _647_ (
    .A(reset),
    .Y(_122_)
  );
  sky130_fd_sc_hd__clkinv_1 _648_ (
    .A(reset),
    .Y(_123_)
  );
  sky130_fd_sc_hd__clkinv_1 _649_ (
    .A(reset),
    .Y(_124_)
  );
  sky130_fd_sc_hd__clkinv_1 _650_ (
    .A(reset),
    .Y(_125_)
  );
  sky130_fd_sc_hd__clkinv_1 _651_ (
    .A(reset),
    .Y(_126_)
  );
  sky130_fd_sc_hd__clkinv_1 _652_ (
    .A(reset),
    .Y(_127_)
  );
  sky130_fd_sc_hd__clkinv_1 _653_ (
    .A(reset),
    .Y(_128_)
  );
  sky130_fd_sc_hd__clkinv_1 _654_ (
    .A(reset),
    .Y(_129_)
  );
  sky130_fd_sc_hd__clkinv_1 _655_ (
    .A(reset),
    .Y(_130_)
  );
  sky130_fd_sc_hd__clkinv_1 _656_ (
    .A(reset),
    .Y(_131_)
  );
  sky130_fd_sc_hd__clkinv_1 _657_ (
    .A(reset),
    .Y(_132_)
  );
  sky130_fd_sc_hd__clkinv_1 _658_ (
    .A(reset),
    .Y(_133_)
  );
  sky130_fd_sc_hd__clkinv_1 _659_ (
    .A(reset),
    .Y(_134_)
  );
  sky130_fd_sc_hd__clkinv_1 _660_ (
    .A(reset),
    .Y(_135_)
  );
  sky130_fd_sc_hd__clkinv_1 _661_ (
    .A(reset),
    .Y(_136_)
  );
  sky130_fd_sc_hd__clkinv_1 _662_ (
    .A(reset),
    .Y(_137_)
  );
  sky130_fd_sc_hd__clkinv_1 _663_ (
    .A(reset),
    .Y(_138_)
  );
  sky130_fd_sc_hd__clkinv_1 _664_ (
    .A(reset),
    .Y(_139_)
  );
  sky130_fd_sc_hd__clkinv_1 _665_ (
    .A(reset),
    .Y(_140_)
  );
  sky130_fd_sc_hd__clkinv_1 _666_ (
    .A(reset),
    .Y(_141_)
  );
  sky130_fd_sc_hd__clkinv_1 _667_ (
    .A(reset),
    .Y(_142_)
  );
  sky130_fd_sc_hd__clkinv_1 _668_ (
    .A(reset),
    .Y(_143_)
  );
  sky130_fd_sc_hd__clkinv_1 _669_ (
    .A(reset),
    .Y(_144_)
  );
  sky130_fd_sc_hd__clkinv_1 _670_ (
    .A(reset),
    .Y(_145_)
  );
  sky130_fd_sc_hd__clkinv_1 _671_ (
    .A(reset),
    .Y(_146_)
  );
  sky130_fd_sc_hd__clkinv_1 _672_ (
    .A(reset),
    .Y(_147_)
  );
  sky130_fd_sc_hd__clkinv_1 _673_ (
    .A(reset),
    .Y(_148_)
  );
  sky130_fd_sc_hd__clkinv_1 _674_ (
    .A(reset),
    .Y(_149_)
  );
  sky130_fd_sc_hd__clkinv_1 _675_ (
    .A(reset),
    .Y(_150_)
  );
  sky130_fd_sc_hd__clkinv_1 _676_ (
    .A(reset),
    .Y(_151_)
  );
  sky130_fd_sc_hd__clkinv_1 _677_ (
    .A(reset),
    .Y(_152_)
  );
  sky130_fd_sc_hd__clkinv_1 _678_ (
    .A(reset),
    .Y(_153_)
  );
  sky130_fd_sc_hd__clkinv_1 _679_ (
    .A(reset),
    .Y(_154_)
  );
  sky130_fd_sc_hd__clkinv_1 _680_ (
    .A(reset),
    .Y(_155_)
  );
  sky130_fd_sc_hd__clkinv_1 _681_ (
    .A(reset),
    .Y(_156_)
  );
  sky130_fd_sc_hd__clkinv_1 _682_ (
    .A(reset),
    .Y(_157_)
  );
  sky130_fd_sc_hd__clkinv_1 _683_ (
    .A(reset),
    .Y(_158_)
  );
  sky130_fd_sc_hd__clkinv_1 _684_ (
    .A(reset),
    .Y(_159_)
  );
  sky130_fd_sc_hd__clkinv_1 _685_ (
    .A(reset),
    .Y(_160_)
  );
  sky130_fd_sc_hd__clkinv_1 _686_ (
    .A(reset),
    .Y(_161_)
  );
  sky130_fd_sc_hd__clkinv_1 _687_ (
    .A(reset),
    .Y(_162_)
  );
  sky130_fd_sc_hd__clkinv_1 _688_ (
    .A(reset),
    .Y(_163_)
  );
  sky130_fd_sc_hd__clkinv_1 _689_ (
    .A(reset),
    .Y(_164_)
  );
  sky130_fd_sc_hd__clkinv_1 _690_ (
    .A(reset),
    .Y(_165_)
  );
  sky130_fd_sc_hd__clkinv_1 _691_ (
    .A(reset),
    .Y(_166_)
  );
  sky130_fd_sc_hd__clkinv_1 _692_ (
    .A(reset),
    .Y(_167_)
  );
  sky130_fd_sc_hd__clkinv_1 _693_ (
    .A(reset),
    .Y(_168_)
  );
  sky130_fd_sc_hd__clkinv_1 _694_ (
    .A(reset),
    .Y(_169_)
  );
  sky130_fd_sc_hd__clkinv_1 _695_ (
    .A(reset),
    .Y(_170_)
  );
  sky130_fd_sc_hd__clkinv_1 _696_ (
    .A(reset),
    .Y(_171_)
  );
  sky130_fd_sc_hd__clkinv_1 _697_ (
    .A(reset),
    .Y(_172_)
  );
  sky130_fd_sc_hd__clkinv_1 _698_ (
    .A(reset),
    .Y(_173_)
  );
  sky130_fd_sc_hd__clkinv_1 _699_ (
    .A(reset),
    .Y(_174_)
  );
  sky130_fd_sc_hd__clkinv_1 _700_ (
    .A(reset),
    .Y(_175_)
  );
  sky130_fd_sc_hd__clkinv_1 _701_ (
    .A(reset),
    .Y(_176_)
  );
  sky130_fd_sc_hd__clkinv_1 _702_ (
    .A(reset),
    .Y(_177_)
  );
  sky130_fd_sc_hd__clkinv_1 _703_ (
    .A(reset),
    .Y(_178_)
  );
  sky130_fd_sc_hd__clkinv_1 _704_ (
    .A(reset),
    .Y(_179_)
  );
  sky130_fd_sc_hd__clkinv_1 _705_ (
    .A(reset),
    .Y(_180_)
  );
  sky130_fd_sc_hd__clkinv_1 _706_ (
    .A(reset),
    .Y(_181_)
  );
  sky130_fd_sc_hd__clkinv_1 _707_ (
    .A(reset),
    .Y(_182_)
  );
  sky130_fd_sc_hd__clkinv_1 _708_ (
    .A(reset),
    .Y(_183_)
  );
  sky130_fd_sc_hd__clkinv_1 _709_ (
    .A(reset),
    .Y(_184_)
  );
  sky130_fd_sc_hd__clkinv_1 _710_ (
    .A(reset),
    .Y(_185_)
  );
  sky130_fd_sc_hd__clkinv_1 _711_ (
    .A(reset),
    .Y(_186_)
  );
  sky130_fd_sc_hd__clkinv_1 _712_ (
    .A(reset),
    .Y(_187_)
  );
  sky130_fd_sc_hd__clkinv_1 _713_ (
    .A(reset),
    .Y(_000_)
  );
  sky130_fd_sc_hd__clkinv_1 _714_ (
    .A(reset),
    .Y(_001_)
  );
  sky130_fd_sc_hd__clkinv_1 _715_ (
    .A(reset),
    .Y(_002_)
  );
  sky130_fd_sc_hd__clkinv_1 _716_ (
    .A(reset),
    .Y(_003_)
  );
  sky130_fd_sc_hd__clkinv_1 _717_ (
    .A(reset),
    .Y(_004_)
  );
  sky130_fd_sc_hd__clkinv_1 _718_ (
    .A(reset),
    .Y(_005_)
  );
  sky130_fd_sc_hd__clkinv_1 _719_ (
    .A(reset),
    .Y(_006_)
  );
  sky130_fd_sc_hd__clkinv_1 _720_ (
    .A(reset),
    .Y(_007_)
  );
  sky130_fd_sc_hd__clkinv_1 _721_ (
    .A(reset),
    .Y(_008_)
  );
  sky130_fd_sc_hd__clkinv_1 _722_ (
    .A(reset),
    .Y(_009_)
  );
  sky130_fd_sc_hd__clkinv_1 _723_ (
    .A(reset),
    .Y(_010_)
  );
  sky130_fd_sc_hd__clkinv_1 _724_ (
    .A(reset),
    .Y(_011_)
  );
  sky130_fd_sc_hd__clkinv_1 _725_ (
    .A(reset),
    .Y(_012_)
  );
  sky130_fd_sc_hd__clkinv_1 _726_ (
    .A(reset),
    .Y(_013_)
  );
  sky130_fd_sc_hd__clkinv_1 _727_ (
    .A(reset),
    .Y(_014_)
  );
  sky130_fd_sc_hd__clkinv_1 _728_ (
    .A(reset),
    .Y(_015_)
  );
  sky130_fd_sc_hd__clkinv_1 _729_ (
    .A(reset),
    .Y(_016_)
  );
  sky130_fd_sc_hd__clkinv_1 _730_ (
    .A(reset),
    .Y(_017_)
  );
  sky130_fd_sc_hd__clkinv_1 _731_ (
    .A(reset),
    .Y(_018_)
  );
  sky130_fd_sc_hd__clkinv_1 _732_ (
    .A(reset),
    .Y(_019_)
  );
  sky130_fd_sc_hd__clkinv_1 _733_ (
    .A(reset),
    .Y(_020_)
  );
  sky130_fd_sc_hd__clkinv_1 _734_ (
    .A(reset),
    .Y(_021_)
  );
  sky130_fd_sc_hd__clkinv_1 _735_ (
    .A(reset),
    .Y(_022_)
  );
  sky130_fd_sc_hd__clkinv_1 _736_ (
    .A(reset),
    .Y(_023_)
  );
  sky130_fd_sc_hd__clkinv_1 _737_ (
    .A(reset),
    .Y(_024_)
  );
  sky130_fd_sc_hd__clkinv_1 _738_ (
    .A(reset),
    .Y(_025_)
  );
  sky130_fd_sc_hd__clkinv_1 _739_ (
    .A(reset),
    .Y(_026_)
  );
  sky130_fd_sc_hd__clkinv_1 _740_ (
    .A(reset),
    .Y(_027_)
  );
  sky130_fd_sc_hd__clkinv_1 _741_ (
    .A(reset),
    .Y(_028_)
  );
  sky130_fd_sc_hd__clkinv_1 _742_ (
    .A(reset),
    .Y(_029_)
  );
  sky130_fd_sc_hd__clkinv_1 _743_ (
    .A(reset),
    .Y(_030_)
  );
  sky130_fd_sc_hd__clkinv_1 _744_ (
    .A(reset),
    .Y(_031_)
  );
  sky130_fd_sc_hd__clkinv_1 _745_ (
    .A(reset),
    .Y(_032_)
  );
  sky130_fd_sc_hd__clkinv_1 _746_ (
    .A(reset),
    .Y(_033_)
  );
  sky130_fd_sc_hd__clkinv_1 _747_ (
    .A(reset),
    .Y(_034_)
  );
  sky130_fd_sc_hd__clkinv_1 _748_ (
    .A(reset),
    .Y(_035_)
  );
  sky130_fd_sc_hd__clkinv_1 _749_ (
    .A(reset),
    .Y(_036_)
  );
  sky130_fd_sc_hd__clkinv_1 _750_ (
    .A(reset),
    .Y(_037_)
  );
  sky130_fd_sc_hd__clkinv_1 _751_ (
    .A(reset),
    .Y(_038_)
  );
  sky130_fd_sc_hd__clkinv_1 _752_ (
    .A(reset),
    .Y(_039_)
  );
  sky130_fd_sc_hd__clkinv_1 _753_ (
    .A(reset),
    .Y(_040_)
  );
  sky130_fd_sc_hd__clkinv_1 _754_ (
    .A(reset),
    .Y(_041_)
  );
  sky130_fd_sc_hd__clkinv_1 _755_ (
    .A(reset),
    .Y(_042_)
  );
  sky130_fd_sc_hd__clkinv_1 _756_ (
    .A(reset),
    .Y(_043_)
  );
  sky130_fd_sc_hd__clkinv_1 _757_ (
    .A(reset),
    .Y(_044_)
  );
  sky130_fd_sc_hd__clkinv_1 _758_ (
    .A(reset),
    .Y(_045_)
  );
  sky130_fd_sc_hd__clkinv_1 _759_ (
    .A(reset),
    .Y(_046_)
  );
  sky130_fd_sc_hd__clkinv_1 _760_ (
    .A(reset),
    .Y(_047_)
  );
  sky130_fd_sc_hd__clkinv_1 _761_ (
    .A(reset),
    .Y(_048_)
  );
  sky130_fd_sc_hd__clkinv_1 _762_ (
    .A(reset),
    .Y(_049_)
  );
  sky130_fd_sc_hd__clkinv_1 _763_ (
    .A(reset),
    .Y(_050_)
  );
  sky130_fd_sc_hd__clkinv_1 _764_ (
    .A(reset),
    .Y(_051_)
  );
  sky130_fd_sc_hd__clkinv_1 _765_ (
    .A(reset),
    .Y(_052_)
  );
  sky130_fd_sc_hd__clkinv_1 _766_ (
    .A(reset),
    .Y(_053_)
  );
  sky130_fd_sc_hd__clkinv_1 _767_ (
    .A(reset),
    .Y(_054_)
  );
  sky130_fd_sc_hd__clkinv_1 _768_ (
    .A(reset),
    .Y(_055_)
  );
  sky130_fd_sc_hd__clkinv_1 _769_ (
    .A(reset),
    .Y(_056_)
  );
  sky130_fd_sc_hd__clkinv_1 _770_ (
    .A(reset),
    .Y(_057_)
  );
  sky130_fd_sc_hd__clkinv_1 _771_ (
    .A(reset),
    .Y(_058_)
  );
  sky130_fd_sc_hd__clkinv_1 _772_ (
    .A(reset),
    .Y(_059_)
  );
  sky130_fd_sc_hd__clkinv_1 _773_ (
    .A(reset),
    .Y(_060_)
  );
  sky130_fd_sc_hd__clkinv_1 _774_ (
    .A(reset),
    .Y(_061_)
  );
  sky130_fd_sc_hd__clkinv_1 _775_ (
    .A(reset),
    .Y(_062_)
  );
  sky130_fd_sc_hd__clkinv_1 _776_ (
    .A(reset),
    .Y(_063_)
  );
  sky130_fd_sc_hd__clkinv_1 _777_ (
    .A(reset),
    .Y(_064_)
  );
  sky130_fd_sc_hd__clkinv_1 _778_ (
    .A(reset),
    .Y(_065_)
  );
  sky130_fd_sc_hd__clkinv_1 _779_ (
    .A(reset),
    .Y(_066_)
  );
  sky130_fd_sc_hd__clkinv_1 _780_ (
    .A(reset),
    .Y(_067_)
  );
  sky130_fd_sc_hd__clkinv_1 _781_ (
    .A(reset),
    .Y(_068_)
  );
  sky130_fd_sc_hd__clkinv_1 _782_ (
    .A(reset),
    .Y(_069_)
  );
  sky130_fd_sc_hd__clkinv_1 _783_ (
    .A(reset),
    .Y(_070_)
  );
  sky130_fd_sc_hd__clkinv_1 _784_ (
    .A(reset),
    .Y(_071_)
  );
  sky130_fd_sc_hd__clkinv_1 _785_ (
    .A(reset),
    .Y(_072_)
  );
  sky130_fd_sc_hd__clkinv_1 _786_ (
    .A(reset),
    .Y(_073_)
  );
  sky130_fd_sc_hd__clkinv_1 _787_ (
    .A(reset),
    .Y(_074_)
  );
  sky130_fd_sc_hd__clkinv_1 _788_ (
    .A(reset),
    .Y(_075_)
  );
  sky130_fd_sc_hd__clkinv_1 _789_ (
    .A(reset),
    .Y(_076_)
  );
  sky130_fd_sc_hd__clkinv_1 _790_ (
    .A(reset),
    .Y(_077_)
  );
  sky130_fd_sc_hd__clkinv_1 _791_ (
    .A(reset),
    .Y(_078_)
  );
  sky130_fd_sc_hd__clkinv_1 _792_ (
    .A(reset),
    .Y(_079_)
  );
  sky130_fd_sc_hd__clkinv_1 _793_ (
    .A(reset),
    .Y(_080_)
  );
  sky130_fd_sc_hd__clkinv_1 _794_ (
    .A(reset),
    .Y(_081_)
  );
  sky130_fd_sc_hd__clkinv_1 _795_ (
    .A(reset),
    .Y(_082_)
  );
  sky130_fd_sc_hd__clkinv_1 _796_ (
    .A(reset),
    .Y(_083_)
  );
  sky130_fd_sc_hd__clkinv_1 _797_ (
    .A(reset),
    .Y(_084_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _798_ (
    .CLK(clk),
    .D(_244_),
    .Q(stored_values[152]),
    .RESET_B(_085_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _799_ (
    .CLK(clk),
    .D(_245_),
    .Q(stored_values[153]),
    .RESET_B(_086_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _800_ (
    .CLK(clk),
    .D(_246_),
    .Q(stored_values[154]),
    .RESET_B(_087_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _801_ (
    .CLK(clk),
    .D(_247_),
    .Q(stored_values[155]),
    .RESET_B(_088_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _802_ (
    .CLK(clk),
    .D(_248_),
    .Q(stored_values[156]),
    .RESET_B(_089_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _803_ (
    .CLK(clk),
    .D(_249_),
    .Q(stored_values[157]),
    .RESET_B(_090_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _804_ (
    .CLK(clk),
    .D(_250_),
    .Q(stored_values[158]),
    .RESET_B(_091_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _805_ (
    .CLK(clk),
    .D(_251_),
    .Q(stored_values[159]),
    .RESET_B(_092_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _806_ (
    .CLK(clk),
    .D(_252_),
    .Q(stored_values[144]),
    .RESET_B(_093_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _807_ (
    .CLK(clk),
    .D(_253_),
    .Q(stored_values[145]),
    .RESET_B(_094_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _808_ (
    .CLK(clk),
    .D(_254_),
    .Q(stored_values[146]),
    .RESET_B(_095_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _809_ (
    .CLK(clk),
    .D(_255_),
    .Q(stored_values[147]),
    .RESET_B(_096_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _810_ (
    .CLK(clk),
    .D(_256_),
    .Q(stored_values[148]),
    .RESET_B(_097_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _811_ (
    .CLK(clk),
    .D(_257_),
    .Q(stored_values[149]),
    .RESET_B(_098_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _812_ (
    .CLK(clk),
    .D(_258_),
    .Q(stored_values[150]),
    .RESET_B(_099_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _813_ (
    .CLK(clk),
    .D(_259_),
    .Q(stored_values[151]),
    .RESET_B(_100_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _814_ (
    .CLK(clk),
    .D(_260_),
    .Q(stored_values[136]),
    .RESET_B(_101_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _815_ (
    .CLK(clk),
    .D(_261_),
    .Q(stored_values[137]),
    .RESET_B(_102_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _816_ (
    .CLK(clk),
    .D(_262_),
    .Q(stored_values[138]),
    .RESET_B(_103_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _817_ (
    .CLK(clk),
    .D(_263_),
    .Q(stored_values[139]),
    .RESET_B(_104_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _818_ (
    .CLK(clk),
    .D(_264_),
    .Q(stored_values[140]),
    .RESET_B(_105_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _819_ (
    .CLK(clk),
    .D(_265_),
    .Q(stored_values[141]),
    .RESET_B(_106_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _820_ (
    .CLK(clk),
    .D(_266_),
    .Q(stored_values[142]),
    .RESET_B(_107_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _821_ (
    .CLK(clk),
    .D(_267_),
    .Q(stored_values[143]),
    .RESET_B(_108_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _822_ (
    .CLK(clk),
    .D(_268_),
    .Q(stored_values[128]),
    .RESET_B(_109_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _823_ (
    .CLK(clk),
    .D(_269_),
    .Q(stored_values[129]),
    .RESET_B(_110_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _824_ (
    .CLK(clk),
    .D(_270_),
    .Q(stored_values[130]),
    .RESET_B(_111_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _825_ (
    .CLK(clk),
    .D(_271_),
    .Q(stored_values[131]),
    .RESET_B(_112_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _826_ (
    .CLK(clk),
    .D(_272_),
    .Q(stored_values[132]),
    .RESET_B(_113_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _827_ (
    .CLK(clk),
    .D(_273_),
    .Q(stored_values[133]),
    .RESET_B(_114_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _828_ (
    .CLK(clk),
    .D(_274_),
    .Q(stored_values[134]),
    .RESET_B(_115_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _829_ (
    .CLK(clk),
    .D(_275_),
    .Q(stored_values[135]),
    .RESET_B(_116_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _830_ (
    .CLK(clk),
    .D(_276_),
    .Q(stored_values[120]),
    .RESET_B(_117_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _831_ (
    .CLK(clk),
    .D(_277_),
    .Q(stored_values[121]),
    .RESET_B(_118_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _832_ (
    .CLK(clk),
    .D(_278_),
    .Q(stored_values[122]),
    .RESET_B(_119_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _833_ (
    .CLK(clk),
    .D(_279_),
    .Q(stored_values[123]),
    .RESET_B(_120_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _834_ (
    .CLK(clk),
    .D(_280_),
    .Q(stored_values[124]),
    .RESET_B(_121_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _835_ (
    .CLK(clk),
    .D(_281_),
    .Q(stored_values[125]),
    .RESET_B(_122_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _836_ (
    .CLK(clk),
    .D(_282_),
    .Q(stored_values[126]),
    .RESET_B(_123_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _837_ (
    .CLK(clk),
    .D(_283_),
    .Q(stored_values[127]),
    .RESET_B(_124_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _838_ (
    .CLK(clk),
    .D(_284_),
    .Q(stored_values[112]),
    .RESET_B(_125_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _839_ (
    .CLK(clk),
    .D(_285_),
    .Q(stored_values[113]),
    .RESET_B(_126_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _840_ (
    .CLK(clk),
    .D(_286_),
    .Q(stored_values[114]),
    .RESET_B(_127_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _841_ (
    .CLK(clk),
    .D(_287_),
    .Q(stored_values[115]),
    .RESET_B(_128_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _842_ (
    .CLK(clk),
    .D(_288_),
    .Q(stored_values[116]),
    .RESET_B(_129_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _843_ (
    .CLK(clk),
    .D(_289_),
    .Q(stored_values[117]),
    .RESET_B(_130_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _844_ (
    .CLK(clk),
    .D(_290_),
    .Q(stored_values[118]),
    .RESET_B(_131_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _845_ (
    .CLK(clk),
    .D(_291_),
    .Q(stored_values[119]),
    .RESET_B(_132_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _846_ (
    .CLK(clk),
    .D(_292_),
    .Q(stored_values[104]),
    .RESET_B(_133_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _847_ (
    .CLK(clk),
    .D(_293_),
    .Q(stored_values[105]),
    .RESET_B(_134_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _848_ (
    .CLK(clk),
    .D(_294_),
    .Q(stored_values[106]),
    .RESET_B(_135_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _849_ (
    .CLK(clk),
    .D(_295_),
    .Q(stored_values[107]),
    .RESET_B(_136_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _850_ (
    .CLK(clk),
    .D(_296_),
    .Q(stored_values[108]),
    .RESET_B(_137_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _851_ (
    .CLK(clk),
    .D(_297_),
    .Q(stored_values[109]),
    .RESET_B(_138_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _852_ (
    .CLK(clk),
    .D(_298_),
    .Q(stored_values[110]),
    .RESET_B(_139_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _853_ (
    .CLK(clk),
    .D(_299_),
    .Q(stored_values[111]),
    .RESET_B(_140_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _854_ (
    .CLK(clk),
    .D(_300_),
    .Q(stored_values[96]),
    .RESET_B(_141_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _855_ (
    .CLK(clk),
    .D(_301_),
    .Q(stored_values[97]),
    .RESET_B(_142_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _856_ (
    .CLK(clk),
    .D(_302_),
    .Q(stored_values[98]),
    .RESET_B(_143_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _857_ (
    .CLK(clk),
    .D(_303_),
    .Q(stored_values[99]),
    .RESET_B(_144_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _858_ (
    .CLK(clk),
    .D(_304_),
    .Q(stored_values[100]),
    .RESET_B(_145_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _859_ (
    .CLK(clk),
    .D(_305_),
    .Q(stored_values[101]),
    .RESET_B(_146_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _860_ (
    .CLK(clk),
    .D(_306_),
    .Q(stored_values[102]),
    .RESET_B(_147_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _861_ (
    .CLK(clk),
    .D(_307_),
    .Q(stored_values[103]),
    .RESET_B(_148_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _862_ (
    .CLK(clk),
    .D(_308_),
    .Q(stored_values[88]),
    .RESET_B(_149_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _863_ (
    .CLK(clk),
    .D(_309_),
    .Q(stored_values[89]),
    .RESET_B(_150_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _864_ (
    .CLK(clk),
    .D(_310_),
    .Q(stored_values[90]),
    .RESET_B(_151_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _865_ (
    .CLK(clk),
    .D(_311_),
    .Q(stored_values[91]),
    .RESET_B(_152_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _866_ (
    .CLK(clk),
    .D(_312_),
    .Q(stored_values[92]),
    .RESET_B(_153_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _867_ (
    .CLK(clk),
    .D(_313_),
    .Q(stored_values[93]),
    .RESET_B(_154_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _868_ (
    .CLK(clk),
    .D(_314_),
    .Q(stored_values[94]),
    .RESET_B(_155_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _869_ (
    .CLK(clk),
    .D(_315_),
    .Q(stored_values[95]),
    .RESET_B(_156_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _870_ (
    .CLK(clk),
    .D(_316_),
    .Q(stored_values[80]),
    .RESET_B(_157_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _871_ (
    .CLK(clk),
    .D(_317_),
    .Q(stored_values[81]),
    .RESET_B(_158_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _872_ (
    .CLK(clk),
    .D(_318_),
    .Q(stored_values[82]),
    .RESET_B(_159_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _873_ (
    .CLK(clk),
    .D(_319_),
    .Q(stored_values[83]),
    .RESET_B(_160_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _874_ (
    .CLK(clk),
    .D(_320_),
    .Q(stored_values[84]),
    .RESET_B(_161_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _875_ (
    .CLK(clk),
    .D(_321_),
    .Q(stored_values[85]),
    .RESET_B(_162_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _876_ (
    .CLK(clk),
    .D(_322_),
    .Q(stored_values[86]),
    .RESET_B(_163_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _877_ (
    .CLK(clk),
    .D(_323_),
    .Q(stored_values[87]),
    .RESET_B(_164_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _878_ (
    .CLK(clk),
    .D(_324_),
    .Q(stored_values[72]),
    .RESET_B(_165_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _879_ (
    .CLK(clk),
    .D(_325_),
    .Q(stored_values[73]),
    .RESET_B(_166_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _880_ (
    .CLK(clk),
    .D(_326_),
    .Q(stored_values[74]),
    .RESET_B(_167_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _881_ (
    .CLK(clk),
    .D(_327_),
    .Q(stored_values[75]),
    .RESET_B(_168_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _882_ (
    .CLK(clk),
    .D(_328_),
    .Q(stored_values[76]),
    .RESET_B(_169_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _883_ (
    .CLK(clk),
    .D(_329_),
    .Q(stored_values[77]),
    .RESET_B(_170_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _884_ (
    .CLK(clk),
    .D(_330_),
    .Q(stored_values[78]),
    .RESET_B(_171_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _885_ (
    .CLK(clk),
    .D(_331_),
    .Q(stored_values[79]),
    .RESET_B(_172_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _886_ (
    .CLK(clk),
    .D(_332_),
    .Q(stored_values[64]),
    .RESET_B(_173_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _887_ (
    .CLK(clk),
    .D(_333_),
    .Q(stored_values[65]),
    .RESET_B(_174_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _888_ (
    .CLK(clk),
    .D(_334_),
    .Q(stored_values[66]),
    .RESET_B(_175_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _889_ (
    .CLK(clk),
    .D(_335_),
    .Q(stored_values[67]),
    .RESET_B(_176_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _890_ (
    .CLK(clk),
    .D(_336_),
    .Q(stored_values[68]),
    .RESET_B(_177_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _891_ (
    .CLK(clk),
    .D(_337_),
    .Q(stored_values[69]),
    .RESET_B(_178_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _892_ (
    .CLK(clk),
    .D(_338_),
    .Q(stored_values[70]),
    .RESET_B(_179_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _893_ (
    .CLK(clk),
    .D(_339_),
    .Q(stored_values[71]),
    .RESET_B(_180_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _894_ (
    .CLK(clk),
    .D(_340_),
    .Q(stored_values[56]),
    .RESET_B(_181_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _895_ (
    .CLK(clk),
    .D(_341_),
    .Q(stored_values[57]),
    .RESET_B(_182_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _896_ (
    .CLK(clk),
    .D(_342_),
    .Q(stored_values[58]),
    .RESET_B(_183_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _897_ (
    .CLK(clk),
    .D(_343_),
    .Q(stored_values[59]),
    .RESET_B(_184_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _898_ (
    .CLK(clk),
    .D(_344_),
    .Q(stored_values[60]),
    .RESET_B(_185_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _899_ (
    .CLK(clk),
    .D(_345_),
    .Q(stored_values[61]),
    .RESET_B(_186_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _900_ (
    .CLK(clk),
    .D(_346_),
    .Q(stored_values[62]),
    .RESET_B(_187_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _901_ (
    .CLK(clk),
    .D(_347_),
    .Q(stored_values[63]),
    .RESET_B(_000_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _902_ (
    .CLK(clk),
    .D(_188_),
    .Q(stored_values[48]),
    .RESET_B(_001_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _903_ (
    .CLK(clk),
    .D(_189_),
    .Q(stored_values[49]),
    .RESET_B(_002_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _904_ (
    .CLK(clk),
    .D(_190_),
    .Q(stored_values[50]),
    .RESET_B(_003_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _905_ (
    .CLK(clk),
    .D(_191_),
    .Q(stored_values[51]),
    .RESET_B(_004_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _906_ (
    .CLK(clk),
    .D(_192_),
    .Q(stored_values[52]),
    .RESET_B(_005_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _907_ (
    .CLK(clk),
    .D(_193_),
    .Q(stored_values[53]),
    .RESET_B(_006_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _908_ (
    .CLK(clk),
    .D(_194_),
    .Q(stored_values[54]),
    .RESET_B(_007_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _909_ (
    .CLK(clk),
    .D(_195_),
    .Q(stored_values[55]),
    .RESET_B(_008_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _910_ (
    .CLK(clk),
    .D(_196_),
    .Q(stored_values[40]),
    .RESET_B(_009_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _911_ (
    .CLK(clk),
    .D(_197_),
    .Q(stored_values[41]),
    .RESET_B(_010_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _912_ (
    .CLK(clk),
    .D(_198_),
    .Q(stored_values[42]),
    .RESET_B(_011_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _913_ (
    .CLK(clk),
    .D(_199_),
    .Q(stored_values[43]),
    .RESET_B(_012_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _914_ (
    .CLK(clk),
    .D(_200_),
    .Q(stored_values[44]),
    .RESET_B(_013_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _915_ (
    .CLK(clk),
    .D(_201_),
    .Q(stored_values[45]),
    .RESET_B(_014_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _916_ (
    .CLK(clk),
    .D(_202_),
    .Q(stored_values[46]),
    .RESET_B(_015_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _917_ (
    .CLK(clk),
    .D(_203_),
    .Q(stored_values[47]),
    .RESET_B(_016_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _918_ (
    .CLK(clk),
    .D(_204_),
    .Q(stored_values[32]),
    .RESET_B(_017_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _919_ (
    .CLK(clk),
    .D(_205_),
    .Q(stored_values[33]),
    .RESET_B(_018_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _920_ (
    .CLK(clk),
    .D(_206_),
    .Q(stored_values[34]),
    .RESET_B(_019_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _921_ (
    .CLK(clk),
    .D(_207_),
    .Q(stored_values[35]),
    .RESET_B(_020_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _922_ (
    .CLK(clk),
    .D(_208_),
    .Q(stored_values[36]),
    .RESET_B(_021_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _923_ (
    .CLK(clk),
    .D(_209_),
    .Q(stored_values[37]),
    .RESET_B(_022_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _924_ (
    .CLK(clk),
    .D(_210_),
    .Q(stored_values[38]),
    .RESET_B(_023_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _925_ (
    .CLK(clk),
    .D(_211_),
    .Q(stored_values[39]),
    .RESET_B(_024_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _926_ (
    .CLK(clk),
    .D(comp[0]),
    .Q(comp_prev[0]),
    .RESET_B(_025_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _927_ (
    .CLK(clk),
    .D(comp[1]),
    .Q(comp_prev[1]),
    .RESET_B(_026_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _928_ (
    .CLK(clk),
    .D(comp[2]),
    .Q(comp_prev[2]),
    .RESET_B(_027_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _929_ (
    .CLK(clk),
    .D(comp[3]),
    .Q(comp_prev[3]),
    .RESET_B(_028_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _930_ (
    .CLK(clk),
    .D(comp[4]),
    .Q(comp_prev[4]),
    .RESET_B(_029_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _931_ (
    .CLK(clk),
    .D(comp[5]),
    .Q(comp_prev[5]),
    .RESET_B(_030_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _932_ (
    .CLK(clk),
    .D(comp[6]),
    .Q(comp_prev[6]),
    .RESET_B(_031_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _933_ (
    .CLK(clk),
    .D(comp[7]),
    .Q(comp_prev[7]),
    .RESET_B(_032_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _934_ (
    .CLK(clk),
    .D(comp[8]),
    .Q(comp_prev[8]),
    .RESET_B(_033_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _935_ (
    .CLK(clk),
    .D(comp[9]),
    .Q(comp_prev[9]),
    .RESET_B(_034_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _936_ (
    .CLK(clk),
    .D(comp[10]),
    .Q(comp_prev[10]),
    .RESET_B(_035_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _937_ (
    .CLK(clk),
    .D(comp[11]),
    .Q(comp_prev[11]),
    .RESET_B(_036_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _938_ (
    .CLK(clk),
    .D(comp[12]),
    .Q(comp_prev[12]),
    .RESET_B(_037_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _939_ (
    .CLK(clk),
    .D(comp[13]),
    .Q(comp_prev[13]),
    .RESET_B(_038_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _940_ (
    .CLK(clk),
    .D(comp[14]),
    .Q(comp_prev[14]),
    .RESET_B(_039_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _941_ (
    .CLK(clk),
    .D(comp[15]),
    .Q(comp_prev[15]),
    .RESET_B(_040_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _942_ (
    .CLK(clk),
    .D(comp[16]),
    .Q(comp_prev[16]),
    .RESET_B(_041_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _943_ (
    .CLK(clk),
    .D(comp[17]),
    .Q(comp_prev[17]),
    .RESET_B(_042_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _944_ (
    .CLK(clk),
    .D(comp[18]),
    .Q(comp_prev[18]),
    .RESET_B(_043_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _945_ (
    .CLK(clk),
    .D(comp[19]),
    .Q(comp_prev[19]),
    .RESET_B(_044_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _946_ (
    .CLK(clk),
    .D(_212_),
    .Q(stored_values[24]),
    .RESET_B(_045_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _947_ (
    .CLK(clk),
    .D(_213_),
    .Q(stored_values[25]),
    .RESET_B(_046_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _948_ (
    .CLK(clk),
    .D(_214_),
    .Q(stored_values[26]),
    .RESET_B(_047_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _949_ (
    .CLK(clk),
    .D(_215_),
    .Q(stored_values[27]),
    .RESET_B(_048_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _950_ (
    .CLK(clk),
    .D(_216_),
    .Q(stored_values[28]),
    .RESET_B(_049_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _951_ (
    .CLK(clk),
    .D(_217_),
    .Q(stored_values[29]),
    .RESET_B(_050_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _952_ (
    .CLK(clk),
    .D(_218_),
    .Q(stored_values[30]),
    .RESET_B(_051_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _953_ (
    .CLK(clk),
    .D(_219_),
    .Q(stored_values[31]),
    .RESET_B(_052_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _954_ (
    .CLK(clk),
    .D(_220_),
    .Q(stored_values[16]),
    .RESET_B(_053_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _955_ (
    .CLK(clk),
    .D(_221_),
    .Q(stored_values[17]),
    .RESET_B(_054_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _956_ (
    .CLK(clk),
    .D(_222_),
    .Q(stored_values[18]),
    .RESET_B(_055_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _957_ (
    .CLK(clk),
    .D(_223_),
    .Q(stored_values[19]),
    .RESET_B(_056_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _958_ (
    .CLK(clk),
    .D(_224_),
    .Q(stored_values[20]),
    .RESET_B(_057_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _959_ (
    .CLK(clk),
    .D(_225_),
    .Q(stored_values[21]),
    .RESET_B(_058_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _960_ (
    .CLK(clk),
    .D(_226_),
    .Q(stored_values[22]),
    .RESET_B(_059_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _961_ (
    .CLK(clk),
    .D(_227_),
    .Q(stored_values[23]),
    .RESET_B(_060_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _962_ (
    .CLK(clk),
    .D(_228_),
    .Q(stored_values[8]),
    .RESET_B(_061_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _963_ (
    .CLK(clk),
    .D(_229_),
    .Q(stored_values[9]),
    .RESET_B(_062_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _964_ (
    .CLK(clk),
    .D(_230_),
    .Q(stored_values[10]),
    .RESET_B(_063_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _965_ (
    .CLK(clk),
    .D(_231_),
    .Q(stored_values[11]),
    .RESET_B(_064_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _966_ (
    .CLK(clk),
    .D(_232_),
    .Q(stored_values[12]),
    .RESET_B(_065_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _967_ (
    .CLK(clk),
    .D(_233_),
    .Q(stored_values[13]),
    .RESET_B(_066_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _968_ (
    .CLK(clk),
    .D(_234_),
    .Q(stored_values[14]),
    .RESET_B(_067_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _969_ (
    .CLK(clk),
    .D(_235_),
    .Q(stored_values[15]),
    .RESET_B(_068_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _970_ (
    .CLK(clk),
    .D(_236_),
    .Q(stored_values[0]),
    .RESET_B(_069_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _971_ (
    .CLK(clk),
    .D(_237_),
    .Q(stored_values[1]),
    .RESET_B(_070_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _972_ (
    .CLK(clk),
    .D(_238_),
    .Q(stored_values[2]),
    .RESET_B(_071_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _973_ (
    .CLK(clk),
    .D(_239_),
    .Q(stored_values[3]),
    .RESET_B(_072_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _974_ (
    .CLK(clk),
    .D(_240_),
    .Q(stored_values[4]),
    .RESET_B(_073_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _975_ (
    .CLK(clk),
    .D(_241_),
    .Q(stored_values[5]),
    .RESET_B(_074_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _976_ (
    .CLK(clk),
    .D(_242_),
    .Q(stored_values[6]),
    .RESET_B(_075_)
  );
  (* src = "single_row_adc.v:25.5-40.8" *)
  sky130_fd_sc_hd__dfrtp_1 _977_ (
    .CLK(clk),
    .D(_243_),
    .Q(stored_values[7]),
    .RESET_B(_076_)
  );
  (* src = "single_row_adc.v:17.5-22.8" *)
  sky130_fd_sc_hd__dfrtp_1 _978_ (
    .CLK(clk),
    .D(_394_[0]),
    .Q(counter[0]),
    .RESET_B(_077_)
  );
  (* src = "single_row_adc.v:17.5-22.8" *)
  sky130_fd_sc_hd__dfrtp_1 _979_ (
    .CLK(clk),
    .D(_395_[1]),
    .Q(counter[1]),
    .RESET_B(_078_)
  );
  (* src = "single_row_adc.v:17.5-22.8" *)
  sky130_fd_sc_hd__dfrtp_1 _980_ (
    .CLK(clk),
    .D(_395_[2]),
    .Q(counter[2]),
    .RESET_B(_079_)
  );
  (* src = "single_row_adc.v:17.5-22.8" *)
  sky130_fd_sc_hd__dfrtp_1 _981_ (
    .CLK(clk),
    .D(_395_[3]),
    .Q(counter[3]),
    .RESET_B(_080_)
  );
  (* src = "single_row_adc.v:17.5-22.8" *)
  sky130_fd_sc_hd__dfrtp_1 _982_ (
    .CLK(clk),
    .D(_395_[4]),
    .Q(counter[4]),
    .RESET_B(_081_)
  );
  (* src = "single_row_adc.v:17.5-22.8" *)
  sky130_fd_sc_hd__dfrtp_1 _983_ (
    .CLK(clk),
    .D(_395_[5]),
    .Q(counter[5]),
    .RESET_B(_082_)
  );
  (* src = "single_row_adc.v:17.5-22.8" *)
  sky130_fd_sc_hd__dfrtp_1 _984_ (
    .CLK(clk),
    .D(_395_[6]),
    .Q(counter[6]),
    .RESET_B(_083_)
  );
  (* src = "single_row_adc.v:17.5-22.8" *)
  sky130_fd_sc_hd__dfrtp_1 _985_ (
    .CLK(clk),
    .D(_395_[7]),
    .Q(counter[7]),
    .RESET_B(_084_)
  );
  assign _394_[7:1] = counter[7:1];
  assign _395_[0] = _394_[0];
endmodule
