/* Generated by Yosys 0.47+56 (git sha1 bbb6bbd12, clang++ 13.0.1 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "edge_detector.v:1.1-20.10" *)
module edge_detector(clk, reset, comp, enable);
  wire _0_;
  (* src = "edge_detector.v:4.17-4.20" *)
  input clk;
  wire clk;
  (* src = "edge_detector.v:6.34-6.38" *)
  input comp;
  wire comp;
  (* src = "edge_detector.v:9.28-9.37" *)
  wire comp_prev;
  (* src = "edge_detector.v:7.35-7.41" *)
  output enable;
  wire enable;
  (* src = "edge_detector.v:5.17-5.22" *)
  input reset;
  wire reset;
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1_ (
    .A(comp),
    .SLEEP(comp_prev),
    .X(enable)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _2_ (
    .A(comp),
    .SLEEP(reset),
    .X(_0_)
  );
  (* src = "edge_detector.v:11.5-16.8" *)
  sky130_fd_sc_hd__dfxtp_1 _3_ (
    .CLK(clk),
    .D(_0_),
    .Q(comp_prev)
  );
endmodule
