/* Generated by Yosys 0.47+56 (git sha1 bbb6bbd12, clang++ 13.0.1 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "negedge_detector.v:1.1-50.10" *)
module negedge_detector(clk, reset, comp, enable);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  (* src = "negedge_detector.v:4.18-4.21" *)
  input clk;
  wire clk;
  (* src = "negedge_detector.v:6.35-6.39" *)
  input comp;
  wire comp;
  (* src = "negedge_detector.v:7.35-7.41" *)
  output enable;
  wire enable;
  (* src = "negedge_detector.v:12.28-12.42" *)
  wire negedge_sample;
  (* src = "negedge_detector.v:5.18-5.23" *)
  input reset;
  wire reset;
  (* src = "negedge_detector.v:13.28-13.39" *)
  wire sample_hold;
  (* src = "negedge_detector.v:14.28-14.50" *)
  wire sample_hold_registered;
  sky130_fd_sc_hd__clkinv_1 _04_ (
    .A(clk),
    .Y(_00_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _05_ (
    .A(comp),
    .SLEEP(reset),
    .X(_01_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _06_ (
    .A(sample_hold),
    .SLEEP(sample_hold_registered),
    .X(enable)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _07_ (
    .A(sample_hold),
    .SLEEP(reset),
    .X(_03_)
  );
  sky130_fd_sc_hd__o21ba_1 _08_ (
    .A1(sample_hold),
    .A2(negedge_sample),
    .B1_N(reset),
    .X(_02_)
  );
  (* src = "negedge_detector.v:20.5-25.8" *)
  sky130_fd_sc_hd__dfxtp_1 _09_ (
    .CLK(_00_),
    .D(_01_),
    .Q(negedge_sample)
  );
  (* src = "negedge_detector.v:28.5-37.8" *)
  sky130_fd_sc_hd__dfxtp_1 _10_ (
    .CLK(clk),
    .D(_02_),
    .Q(sample_hold)
  );
  (* src = "negedge_detector.v:40.5-45.8" *)
  sky130_fd_sc_hd__dfxtp_1 _11_ (
    .CLK(clk),
    .D(_03_),
    .Q(sample_hold_registered)
  );
endmodule
