/* Generated by Yosys 0.47+56 (git sha1 bbb6bbd12, clang++ 13.0.1 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "register_array.v:1.1-23.10" *)
module register_array(clk, reset, enable, count, stored_values);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  (* src = "register_array.v:4.17-4.20" *)
  input clk;
  wire clk;
  (* src = "register_array.v:7.23-7.28" *)
  input [7:0] count;
  wire [7:0] count;
  (* src = "register_array.v:6.34-6.40" *)
  input enable;
  wire enable;
  (* src = "register_array.v:5.17-5.22" *)
  input reset;
  wire reset;
  (* src = "register_array.v:8.41-8.54" *)
  output [7:0] stored_values;
  wire [7:0] stored_values;
  sky130_fd_sc_hd__mux2i_1 _16_ (
    .A0(stored_values[0]),
    .A1(count[0]),
    .S(enable),
    .Y(_08_)
  );
  sky130_fd_sc_hd__nor2_1 _17_ (
    .A(reset),
    .B(_08_),
    .Y(_00_)
  );
  sky130_fd_sc_hd__mux2i_1 _18_ (
    .A0(stored_values[1]),
    .A1(count[1]),
    .S(enable),
    .Y(_09_)
  );
  sky130_fd_sc_hd__nor2_1 _19_ (
    .A(reset),
    .B(_09_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__mux2i_1 _20_ (
    .A0(stored_values[2]),
    .A1(count[2]),
    .S(enable),
    .Y(_10_)
  );
  sky130_fd_sc_hd__nor2_1 _21_ (
    .A(reset),
    .B(_10_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__mux2i_1 _22_ (
    .A0(stored_values[3]),
    .A1(count[3]),
    .S(enable),
    .Y(_11_)
  );
  sky130_fd_sc_hd__nor2_1 _23_ (
    .A(reset),
    .B(_11_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__mux2i_1 _24_ (
    .A0(stored_values[4]),
    .A1(count[4]),
    .S(enable),
    .Y(_12_)
  );
  sky130_fd_sc_hd__nor2_1 _25_ (
    .A(reset),
    .B(_12_),
    .Y(_04_)
  );
  sky130_fd_sc_hd__mux2i_1 _26_ (
    .A0(stored_values[5]),
    .A1(count[5]),
    .S(enable),
    .Y(_13_)
  );
  sky130_fd_sc_hd__nor2_1 _27_ (
    .A(reset),
    .B(_13_),
    .Y(_05_)
  );
  sky130_fd_sc_hd__mux2i_1 _28_ (
    .A0(stored_values[6]),
    .A1(count[6]),
    .S(enable),
    .Y(_14_)
  );
  sky130_fd_sc_hd__nor2_1 _29_ (
    .A(reset),
    .B(_14_),
    .Y(_06_)
  );
  sky130_fd_sc_hd__mux2i_1 _30_ (
    .A0(stored_values[7]),
    .A1(count[7]),
    .S(enable),
    .Y(_15_)
  );
  sky130_fd_sc_hd__nor2_1 _31_ (
    .A(reset),
    .B(_15_),
    .Y(_07_)
  );
  (* src = "register_array.v:10.5-21.8" *)
  sky130_fd_sc_hd__dfxtp_1 _32_ (
    .CLK(clk),
    .D(_00_),
    .Q(stored_values[0])
  );
  (* src = "register_array.v:10.5-21.8" *)
  sky130_fd_sc_hd__dfxtp_1 _33_ (
    .CLK(clk),
    .D(_01_),
    .Q(stored_values[1])
  );
  (* src = "register_array.v:10.5-21.8" *)
  sky130_fd_sc_hd__dfxtp_1 _34_ (
    .CLK(clk),
    .D(_02_),
    .Q(stored_values[2])
  );
  (* src = "register_array.v:10.5-21.8" *)
  sky130_fd_sc_hd__dfxtp_1 _35_ (
    .CLK(clk),
    .D(_03_),
    .Q(stored_values[3])
  );
  (* src = "register_array.v:10.5-21.8" *)
  sky130_fd_sc_hd__dfxtp_1 _36_ (
    .CLK(clk),
    .D(_04_),
    .Q(stored_values[4])
  );
  (* src = "register_array.v:10.5-21.8" *)
  sky130_fd_sc_hd__dfxtp_1 _37_ (
    .CLK(clk),
    .D(_05_),
    .Q(stored_values[5])
  );
  (* src = "register_array.v:10.5-21.8" *)
  sky130_fd_sc_hd__dfxtp_1 _38_ (
    .CLK(clk),
    .D(_06_),
    .Q(stored_values[6])
  );
  (* src = "register_array.v:10.5-21.8" *)
  sky130_fd_sc_hd__dfxtp_1 _39_ (
    .CLK(clk),
    .D(_07_),
    .Q(stored_values[7])
  );
endmodule
