/* Generated by Yosys 0.47+56 (git sha1 bbb6bbd12, clang++ 13.0.1 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "counter.v:3.1-16.10" *)
module counter(Clk, Rst, Cnt_en, Cnt);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  (* src = "counter.v:4.15-4.18" *)
  input Clk;
  wire Clk;
  (* src = "counter.v:5.31-5.34" *)
  output [7:0] Cnt;
  wire [7:0] Cnt;
  (* src = "counter.v:4.25-4.31" *)
  input Cnt_en;
  wire Cnt_en;
  (* src = "counter.v:4.20-4.23" *)
  input Rst;
  wire Rst;
  sky130_fd_sc_hd__and3_1 _21_ (
    .A(Cnt_en),
    .B(Cnt[1]),
    .C(Cnt[0]),
    .X(_08_)
  );
  sky130_fd_sc_hd__and4_1 _22_ (
    .A(Cnt[2]),
    .B(Cnt_en),
    .C(Cnt[1]),
    .D(Cnt[0]),
    .X(_09_)
  );
  sky130_fd_sc_hd__and2_0 _23_ (
    .A(Cnt[3]),
    .B(_09_),
    .X(_10_)
  );
  sky130_fd_sc_hd__nor2_1 _24_ (
    .A(Cnt[3]),
    .B(_09_),
    .Y(_11_)
  );
  sky130_fd_sc_hd__nor3_1 _25_ (
    .A(Rst),
    .B(_10_),
    .C(_11_),
    .Y(_00_)
  );
  sky130_fd_sc_hd__o21bai_1 _26_ (
    .A1(Cnt[4]),
    .A2(_10_),
    .B1_N(Rst),
    .Y(_12_)
  );
  sky130_fd_sc_hd__a21oi_1 _27_ (
    .A1(Cnt[4]),
    .A2(_10_),
    .B1(_12_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__and4_1 _28_ (
    .A(Cnt[5]),
    .B(Cnt[4]),
    .C(Cnt[3]),
    .D(_09_),
    .X(_13_)
  );
  sky130_fd_sc_hd__a21oi_1 _29_ (
    .A1(Cnt[4]),
    .A2(_10_),
    .B1(Cnt[5]),
    .Y(_14_)
  );
  sky130_fd_sc_hd__nor3_1 _30_ (
    .A(Rst),
    .B(_13_),
    .C(_14_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__o21bai_1 _31_ (
    .A1(Cnt[6]),
    .A2(_13_),
    .B1_N(Rst),
    .Y(_15_)
  );
  sky130_fd_sc_hd__a21oi_1 _32_ (
    .A1(Cnt[6]),
    .A2(_13_),
    .B1(_15_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__and3_1 _33_ (
    .A(Cnt[7]),
    .B(Cnt[6]),
    .C(_13_),
    .X(_16_)
  );
  sky130_fd_sc_hd__a21oi_1 _34_ (
    .A1(Cnt[6]),
    .A2(_13_),
    .B1(Cnt[7]),
    .Y(_17_)
  );
  sky130_fd_sc_hd__nor3_1 _35_ (
    .A(Rst),
    .B(_16_),
    .C(_17_),
    .Y(_04_)
  );
  sky130_fd_sc_hd__a21oi_1 _36_ (
    .A1(Cnt_en),
    .A2(Cnt[0]),
    .B1(Rst),
    .Y(_18_)
  );
  sky130_fd_sc_hd__o21a_1 _37_ (
    .A1(Cnt_en),
    .A2(Cnt[0]),
    .B1(_18_),
    .X(_05_)
  );
  sky130_fd_sc_hd__a21oi_1 _38_ (
    .A1(Cnt_en),
    .A2(Cnt[0]),
    .B1(Cnt[1]),
    .Y(_19_)
  );
  sky130_fd_sc_hd__nor3_1 _39_ (
    .A(Rst),
    .B(_08_),
    .C(_19_),
    .Y(_06_)
  );
  sky130_fd_sc_hd__nor2_1 _40_ (
    .A(Cnt[2]),
    .B(_08_),
    .Y(_20_)
  );
  sky130_fd_sc_hd__nor3_1 _41_ (
    .A(Rst),
    .B(_09_),
    .C(_20_),
    .Y(_07_)
  );
  (* src = "counter.v:9.4-15.7" *)
  sky130_fd_sc_hd__dfxtp_1 _42_ (
    .CLK(Clk),
    .D(_00_),
    .Q(Cnt[3])
  );
  (* src = "counter.v:9.4-15.7" *)
  sky130_fd_sc_hd__dfxtp_1 _43_ (
    .CLK(Clk),
    .D(_01_),
    .Q(Cnt[4])
  );
  (* src = "counter.v:9.4-15.7" *)
  sky130_fd_sc_hd__dfxtp_1 _44_ (
    .CLK(Clk),
    .D(_02_),
    .Q(Cnt[5])
  );
  (* src = "counter.v:9.4-15.7" *)
  sky130_fd_sc_hd__dfxtp_1 _45_ (
    .CLK(Clk),
    .D(_03_),
    .Q(Cnt[6])
  );
  (* src = "counter.v:9.4-15.7" *)
  sky130_fd_sc_hd__dfxtp_1 _46_ (
    .CLK(Clk),
    .D(_04_),
    .Q(Cnt[7])
  );
  (* src = "counter.v:9.4-15.7" *)
  sky130_fd_sc_hd__dfxtp_1 _47_ (
    .CLK(Clk),
    .D(_05_),
    .Q(Cnt[0])
  );
  (* src = "counter.v:9.4-15.7" *)
  sky130_fd_sc_hd__dfxtp_1 _48_ (
    .CLK(Clk),
    .D(_06_),
    .Q(Cnt[1])
  );
  (* src = "counter.v:9.4-15.7" *)
  sky130_fd_sc_hd__dfxtp_1 _49_ (
    .CLK(Clk),
    .D(_07_),
    .Q(Cnt[2])
  );
endmodule
