/* Generated by Yosys 0.47+56 (git sha1 bbb6bbd12, clang++ 13.0.1 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "edge_detector.v:1.1-20.10" *)
module edge_detector(clk, reset, comp, enable);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  (* src = "edge_detector.v:4.17-4.20" *)
  input clk;
  wire clk;
  (* src = "edge_detector.v:6.34-6.38" *)
  input [4:0] comp;
  wire [4:0] comp;
  (* src = "edge_detector.v:9.28-9.37" *)
  wire [4:0] comp_prev;
  (* src = "edge_detector.v:7.35-7.41" *)
  output [4:0] enable;
  wire [4:0] enable;
  (* src = "edge_detector.v:5.17-5.22" *)
  input reset;
  wire reset;
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _05_ (
    .A(comp[0]),
    .SLEEP(comp_prev[0]),
    .X(enable[0])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _06_ (
    .A(comp[1]),
    .SLEEP(comp_prev[1]),
    .X(enable[1])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _07_ (
    .A(comp[2]),
    .SLEEP(comp_prev[2]),
    .X(enable[2])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _08_ (
    .A(comp[3]),
    .SLEEP(comp_prev[3]),
    .X(enable[3])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _09_ (
    .A(comp[4]),
    .SLEEP(comp_prev[4]),
    .X(enable[4])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _10_ (
    .A(comp[4]),
    .SLEEP(reset),
    .X(_00_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _11_ (
    .A(comp[0]),
    .SLEEP(reset),
    .X(_01_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _12_ (
    .A(comp[1]),
    .SLEEP(reset),
    .X(_02_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _13_ (
    .A(comp[2]),
    .SLEEP(reset),
    .X(_03_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _14_ (
    .A(comp[3]),
    .SLEEP(reset),
    .X(_04_)
  );
  (* src = "edge_detector.v:11.5-16.8" *)
  sky130_fd_sc_hd__dfxtp_1 _15_ (
    .CLK(clk),
    .D(_00_),
    .Q(comp_prev[4])
  );
  (* src = "edge_detector.v:11.5-16.8" *)
  sky130_fd_sc_hd__dfxtp_1 _16_ (
    .CLK(clk),
    .D(_01_),
    .Q(comp_prev[0])
  );
  (* src = "edge_detector.v:11.5-16.8" *)
  sky130_fd_sc_hd__dfxtp_1 _17_ (
    .CLK(clk),
    .D(_02_),
    .Q(comp_prev[1])
  );
  (* src = "edge_detector.v:11.5-16.8" *)
  sky130_fd_sc_hd__dfxtp_1 _18_ (
    .CLK(clk),
    .D(_03_),
    .Q(comp_prev[2])
  );
  (* src = "edge_detector.v:11.5-16.8" *)
  sky130_fd_sc_hd__dfxtp_1 _19_ (
    .CLK(clk),
    .D(_04_),
    .Q(comp_prev[3])
  );
endmodule
